<script lang="ts">
  // @generated by ui-generator — do not edit

	import UnderlineIcon from "@lucide/svelte/icons/underline";
	import { Toggle } from "../index.js";
</script>

<Toggle aria-label="Toggle underline" disabled>
	<UnderlineIcon class="size-4" />
</Toggle>
