<script lang="ts">
  // @generated by ui-generator — do not edit

  import BookmarkIcon from "@lucide/svelte/icons/bookmark";
  import { Toggle } from "../index.js";
</script>

<Toggle
  aria-label="Toggle bookmark"
  size="sm"
  variant="outline"
  class="data-[state=on]:bg-transparent data-[state=on]:*:[svg]:fill-blue-500 data-[state=on]:*:[svg]:stroke-blue-500"
>
  <BookmarkIcon />
  Bookmark
</Toggle>
