<script lang="ts">
  // @generated by ui-generator — do not edit

	import ItalicIcon from "@lucide/svelte/icons/italic";
	import { Toggle } from "../index.js";
</script>

<Toggle size="sm" aria-label="Toggle italic">
	<ItalicIcon class="size-4" />
</Toggle>
