<script lang="ts">
  // @generated by ui-generator — do not edit

	import ItalicIcon from "@lucide/svelte/icons/italic";
	import { Toggle } from "../index.js";
</script>

<Toggle aria-label="Toggle italic">
	<ItalicIcon class="me-2 size-4" />
	Italic
</Toggle>
