<script module lang="ts">
  // @generated by ui-generator — do not edit
  import { defineMeta } from "@storybook/addon-svelte-csf";
  import * as AlertDialog from "./index.js";
  import * as exampleSources from "./AlertDialog.example-sources.js";
  import PreviewExample from "./examples/preview.svelte";

  const { Story } = defineMeta({
    title: "Shadcn/Overlays/Alert Dialog",
    component: AlertDialog.AlertDialog,
  });
</script>

<Story
  name="Preview"
  exportName="Preview"
  tags={["upstream-example"]}
  parameters={{
    a11y: { test: "todo" },
    docs: {
      description: {
        story: "A modal dialog that interrupts the user with important content and expects a response.\n\n[Docs](https://bits-ui.com/docs/components/alert-dialog)\n\n[API Reference](https://bits-ui.com/docs/components/alert-dialog#api-reference)",
      },
      source: {
        code: exampleSources.Preview,
        language: "html",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <PreviewExample />
    </div>
  {/snippet}
</Story>
