/**
 * Public CSS custom properties for `@lapismd/design-core/workspace`.
 *
 * Defaults live in `workspace.tokens.css`. Consumers override these values on
 * `:root` or a Workspace ancestor.
 */
export const workspaceTokenNames = {
  background: "--ui-workspace-background",
  foreground: "--ui-workspace-foreground",
  viewBackground: "--ui-workspace-view-background",
  viewSecondaryBackground: "--ui-workspace-view-secondary-background",
  viewForeground: "--ui-workspace-view-foreground",
  panel: "--ui-workspace-panel",
  panelForeground: "--ui-workspace-panel-foreground",
  panelActionHoverBackground: "--ui-workspace-panel-action-hover-background",
  panelActionHoverForeground: "--ui-workspace-panel-action-hover-foreground",
  muted: "--ui-workspace-muted",
  mutedForeground: "--ui-workspace-muted-foreground",
  popover: "--ui-workspace-popover",
  popoverForeground: "--ui-workspace-popover-foreground",
  border: "--ui-workspace-border",
  borderStrong: "--ui-workspace-border-strong",
  accent: "--ui-workspace-accent",
  accentForeground: "--ui-workspace-accent-foreground",
  secondary: "--ui-workspace-secondary",
  secondaryForeground: "--ui-workspace-secondary-foreground",
  aboutPrimaryForeground: "--ui-workspace-about-primary-foreground",
  selection: "--ui-workspace-selection",
  destructive: "--ui-workspace-destructive",
  warning: "--ui-workspace-warning",
  diagnosticError: "--ui-workspace-diagnostic-error",
  diagnosticWarning: "--ui-workspace-diagnostic-warning",
  diagnosticInformation: "--ui-workspace-diagnostic-information",
  diagnosticHint: "--ui-workspace-diagnostic-hint",
  focusRing: "--ui-workspace-focus-ring",
  fontSans: "--ui-workspace-font-sans",
  fontMono: "--ui-workspace-font-mono",
  radiusSmall: "--ui-workspace-radius-small",
  radiusMedium: "--ui-workspace-radius-medium",
  radiusLarge: "--ui-workspace-radius-large",
  shadow: "--ui-workspace-shadow",
  tabHeight: "--ui-workspace-tab-height",
  tabActiveHeight: "--ui-workspace-tab-active-height",
  tabWidth: "--ui-workspace-tab-width",
  tabMaxWidth: "--ui-workspace-tab-max-width",
  tabCurve: "--ui-workspace-tab-curve",
  tabActiveBackground: "--ui-workspace-tab-active-background",
  tabHoverBackground: "--ui-workspace-tab-hover-background",
  tabContainerBackground: "--ui-workspace-tab-container-background",
  tabDivider: "--ui-workspace-tab-divider",
  stackedShadow: "--ui-workspace-stacked-shadow",
  stackedPaneWidth: "--ui-workspace-stacked-pane-width",
  sidebarHeaderHeight: "--ui-workspace-sidebar-header-height",
  bottomPanelMinHeight: "--ui-workspace-bottom-panel-min-height",
  bottomPanelMaxHeight: "--ui-workspace-bottom-panel-max-height",
  bottomPanelCollapsedWidth: "--ui-workspace-bottom-panel-collapsed-width",
  ribbonWidth: "--ui-workspace-ribbon-width",
  statusHeight: "--ui-workspace-status-height",
  settingsHeadingSize: "--ui-workspace-settings-heading-size",
  settingsHeadingWeight: "--ui-workspace-settings-heading-weight",
  settingsLabelSize: "--ui-workspace-settings-label-size",
  settingsDescriptionSize: "--ui-workspace-settings-description-size",
  settingsNavigationRowHeight: "--ui-workspace-settings-navigation-row-height",
  settingsNavigationActiveBackground:
    "--ui-workspace-settings-navigation-active-background",
  settingsControlHeight: "--ui-workspace-settings-control-height",
  settingsControlRadius: "--ui-workspace-settings-control-radius",
  settingsDialogRadius: "--ui-workspace-settings-dialog-radius",
  settingsDialogMaxWidth: "--ui-workspace-settings-dialog-max-width",
  settingsDialogHeight: "--ui-workspace-settings-dialog-height",
  overlayZIndex: "--ui-workspace-overlay-z-index",
  explorerToolbarHeight: "--ui-workspace-explorer-toolbar-height",
  explorerRowHoverBackground: "--ui-workspace-explorer-row-hover-background",
  explorerRowActiveBackground: "--ui-workspace-explorer-row-active-background",
  explorerDropBackground: "--ui-workspace-explorer-drop-background",
  explorerDropForeground: "--ui-workspace-explorer-drop-foreground",
  explorerDropRadius: "--ui-workspace-explorer-drop-radius",
  explorerDropPaddingEnd: "--ui-workspace-explorer-drop-padding-end",
  explorerToolbarActionHoverBackground:
    "--ui-workspace-explorer-toolbar-action-hover-background",
  explorerToolbarActionHoverForeground:
    "--ui-workspace-explorer-toolbar-action-hover-foreground",
  explorerFlashRing: "--ui-workspace-explorer-flash-ring",
  explorerRowBorderWidth: "--ui-workspace-explorer-row-border-width",
  explorerRowPaddingInline: "--ui-workspace-explorer-row-padding-inline",
  explorerIndent: "--ui-workspace-explorer-indent",
  explorerGuideWidth: "--ui-workspace-explorer-guide-width",
  explorerGuideColor: "--ui-workspace-explorer-guide-color",
  explorerGuideGap: "--ui-workspace-explorer-guide-gap",
  explorerFontFamily: "--ui-workspace-explorer-font-family",
  explorerFontSize: "--ui-workspace-explorer-font-size",
  explorerRowHeight: "--ui-workspace-explorer-row-height",
  explorerRowGap: "--ui-workspace-explorer-row-gap",
  explorerRowActiveWeight: "--ui-workspace-explorer-row-active-weight",
  explorerContentPadding: "--ui-workspace-explorer-content-padding",
  startupBackground: "--ui-workspace-startup-background",
  startupMaxWidth: "--ui-workspace-startup-max-width",
  startupPadding: "--ui-workspace-startup-padding",
  startupTitleSize: "--ui-workspace-startup-title-size",
  startupProgressHeight: "--ui-workspace-startup-progress-height",
  startupProgressBackground: "--ui-workspace-startup-progress-background",
  startupTaskBackground: "--ui-workspace-startup-task-background",
  startupTaskActiveBackground: "--ui-workspace-startup-task-active-background",
  startupTaskCompleteBackground:
    "--ui-workspace-startup-task-complete-background",
  startupFailureBackground: "--ui-workspace-startup-failure-background",
  startupFailurePadding: "--ui-workspace-startup-failure-padding",
} as const;

export type WorkspaceTokenKey = keyof typeof workspaceTokenNames;
export type WorkspaceToken = (typeof workspaceTokenNames)[WorkspaceTokenKey];

/** Default bindings from `workspace.tokens.css`. */
export const workspaceTokenDefaults: Record<WorkspaceTokenKey, string> = {
  background: "var(--background)",
  foreground: "var(--foreground)",
  viewBackground: "var(--ui-workspace-background)",
  viewSecondaryBackground: "var(--ui-workspace-secondary)",
  viewForeground: "var(--ui-workspace-foreground)",
  panel: "var(--sidebar, var(--background))",
  panelForeground: "var(--sidebar-foreground, var(--foreground))",
  panelActionHoverBackground: "var(--sidebar-accent, var(--accent))",
  panelActionHoverForeground:
    "var(--sidebar-accent-foreground, var(--ui-workspace-panel-foreground))",
  muted: "var(--muted)",
  mutedForeground: "var(--muted-foreground)",
  popover: "var(--popover)",
  popoverForeground: "var(--popover-foreground)",
  border: "var(--border)",
  borderStrong: "color-mix(in srgb, var(--foreground) 18%, var(--border))",
  accent: "var(--primary)",
  accentForeground: "var(--primary-foreground)",
  secondary: "var(--secondary)",
  secondaryForeground: "var(--secondary-foreground)",
  aboutPrimaryForeground:
    "color-mix(in srgb, var(--ui-workspace-accent) 15%, #000)",
  selection: "color-mix(in srgb, var(--primary) 14%, transparent)",
  destructive: "var(--destructive)",
  warning: "var(--warning, #f97316)",
  diagnosticError: "var(--ui-workspace-destructive)",
  diagnosticWarning: "var(--ui-workspace-warning)",
  diagnosticInformation: "var(--ui-workspace-accent)",
  diagnosticHint: "var(--ui-workspace-muted-foreground)",
  focusRing: "var(--ring)",
  fontSans: "var(--font-sans, inherit)",
  fontMono: "var(--font-mono, ui-monospace, SFMono-Regular, Menlo, monospace)",
  radiusSmall: "calc(var(--radius, 0.625rem) * 0.6)",
  radiusMedium: "calc(var(--radius, 0.625rem) * 0.8)",
  radiusLarge: "var(--radius, 0.625rem)",
  shadow: "0 12px 32px rgb(15 23 42 / 24%)",
  tabHeight: "2.5rem",
  tabActiveHeight: "2.25rem",
  tabWidth: "12.5rem",
  tabMaxWidth: "20rem",
  tabCurve: "0.375rem",
  tabActiveBackground: "var(--background)",
  tabHoverBackground: "var(--accent)",
  tabContainerBackground: "var(--sidebar, var(--ui-workspace-muted))",
  tabDivider: "var(--border)",
  stackedShadow: "-0.5rem 0 0.5rem rgb(0 0 0 / 5%)",
  stackedPaneWidth: "43.75rem",
  sidebarHeaderHeight: "2rem",
  bottomPanelMinHeight: "7.5rem",
  bottomPanelMaxHeight: "70%",
  bottomPanelCollapsedWidth: "2rem",
  ribbonWidth: "3rem",
  statusHeight: "1.5rem",
  settingsHeadingSize: "1rem",
  settingsHeadingWeight: "400",
  settingsLabelSize: "0.9375rem",
  settingsDescriptionSize: "0.75rem",
  settingsNavigationRowHeight: "2rem",
  settingsNavigationActiveBackground: "var(--ui-workspace-selection)",
  settingsControlHeight: "1.875rem",
  settingsControlRadius: "0.375rem",
  settingsDialogRadius: "0.5rem",
  settingsDialogMaxWidth: "68.75rem",
  settingsDialogHeight: "85vh",
  overlayZIndex: "50",
  explorerToolbarHeight: "var(--ui-workspace-sidebar-header-height)",
  explorerRowHoverBackground:
    "var(--ui-workspace-panel-action-hover-background)",
  explorerRowActiveBackground:
    "var(--ui-workspace-explorer-row-hover-background)",
  explorerDropBackground:
    "color-mix(in srgb, var(--ui-workspace-accent) 10%, transparent)",
  explorerDropForeground: "var(--ui-workspace-accent)",
  explorerDropRadius: "var(--ui-workspace-radius-small)",
  explorerDropPaddingEnd: "0.25rem",
  explorerToolbarActionHoverBackground:
    "color-mix(in srgb, var(--ui-workspace-foreground) 14%, var(--ui-workspace-panel))",
  explorerToolbarActionHoverForeground: "var(--ui-workspace-panel-foreground)",
  explorerFlashRing: "var(--ui-workspace-accent)",
  explorerRowBorderWidth: "2px",
  explorerRowPaddingInline: "0.375rem",
  explorerIndent:
    "calc(var(--ui-workspace-explorer-row-border-width) + var(--ui-workspace-explorer-row-padding-inline) + (var(--ui-workspace-icon-size, 1rem) / 2) - (var(--ui-workspace-explorer-guide-width) / 2))",
  explorerGuideWidth: "1px",
  explorerGuideColor:
    "color-mix(in srgb, var(--ui-workspace-foreground) 22%, transparent)",
  explorerGuideGap: "0.5rem",
  explorerFontFamily: "var(--ui-workspace-font-sans)",
  explorerFontSize: "0.8125rem",
  explorerRowHeight: "1.75rem",
  explorerRowGap: "0.125rem",
  explorerRowActiveWeight: "inherit",
  explorerContentPadding: "0.5rem",
  startupBackground: "var(--ui-workspace-background)",
  startupMaxWidth: "32rem",
  startupPadding: "1.5rem",
  startupTitleSize: "1.125rem",
  startupProgressHeight: "0.5rem",
  startupProgressBackground:
    "color-mix(in srgb, var(--ui-workspace-accent) 20%, transparent)",
  startupTaskBackground: "var(--ui-workspace-background)",
  startupTaskActiveBackground:
    "color-mix(in srgb, var(--ui-workspace-accent) 5%, var(--ui-workspace-background))",
  startupTaskCompleteBackground:
    "color-mix(in srgb, var(--ui-workspace-muted) 40%, var(--ui-workspace-background))",
  startupFailureBackground: "var(--ui-workspace-background)",
  startupFailurePadding: "1.5rem",
};
