/**
 * Public CSS custom properties for `@lapismd/design-core/workspace`.
 *
 * Defaults live in `workspace.tokens.css`. Consumers override these values on
 * `:root` or a Workspace ancestor.
 */
export const workspaceTokenNames = {
  background: "--ui-workspace-background",
  foreground: "--ui-workspace-foreground",
  panel: "--ui-workspace-panel",
  panelForeground: "--ui-workspace-panel-foreground",
  muted: "--ui-workspace-muted",
  mutedForeground: "--ui-workspace-muted-foreground",
  popover: "--ui-workspace-popover",
  popoverForeground: "--ui-workspace-popover-foreground",
  border: "--ui-workspace-border",
  borderStrong: "--ui-workspace-border-strong",
  accent: "--ui-workspace-accent",
  accentForeground: "--ui-workspace-accent-foreground",
  aboutPrimaryForeground: "--ui-workspace-about-primary-foreground",
  selection: "--ui-workspace-selection",
  destructive: "--ui-workspace-destructive",
  warning: "--ui-workspace-warning",
  focusRing: "--ui-workspace-focus-ring",
  fontSans: "--ui-workspace-font-sans",
  fontMono: "--ui-workspace-font-mono",
  radiusSmall: "--ui-workspace-radius-small",
  radiusMedium: "--ui-workspace-radius-medium",
  radiusLarge: "--ui-workspace-radius-large",
  shadow: "--ui-workspace-shadow",
  tabHeight: "--ui-workspace-tab-height",
  tabActiveHeight: "--ui-workspace-tab-active-height",
  tabWidth: "--ui-workspace-tab-width",
  tabMaxWidth: "--ui-workspace-tab-max-width",
  tabCurve: "--ui-workspace-tab-curve",
  tabActiveBackground: "--ui-workspace-tab-active-background",
  tabContainerBackground: "--ui-workspace-tab-container-background",
  tabDivider: "--ui-workspace-tab-divider",
  stackedShadow: "--ui-workspace-stacked-shadow",
  stackedPaneWidth: "--ui-workspace-stacked-pane-width",
  sidebarHeaderHeight: "--ui-workspace-sidebar-header-height",
  ribbonWidth: "--ui-workspace-ribbon-width",
  statusHeight: "--ui-workspace-status-height",
  settingsHeadingSize: "--ui-workspace-settings-heading-size",
  settingsHeadingWeight: "--ui-workspace-settings-heading-weight",
  settingsLabelSize: "--ui-workspace-settings-label-size",
  settingsDescriptionSize: "--ui-workspace-settings-description-size",
  settingsNavigationRowHeight: "--ui-workspace-settings-navigation-row-height",
  settingsNavigationActiveBackground:
    "--ui-workspace-settings-navigation-active-background",
  settingsControlHeight: "--ui-workspace-settings-control-height",
  settingsControlRadius: "--ui-workspace-settings-control-radius",
  settingsDialogRadius: "--ui-workspace-settings-dialog-radius",
  settingsDialogMaxWidth: "--ui-workspace-settings-dialog-max-width",
  settingsDialogHeight: "--ui-workspace-settings-dialog-height",
  overlayZIndex: "--ui-workspace-overlay-z-index",
} as const;

export type WorkspaceTokenKey = keyof typeof workspaceTokenNames;
export type WorkspaceToken = (typeof workspaceTokenNames)[WorkspaceTokenKey];

/** Default bindings from `workspace.tokens.css`. */
export const workspaceTokenDefaults: Record<WorkspaceTokenKey, string> = {
  background: "var(--background)",
  foreground: "var(--foreground)",
  panel: "var(--sidebar, var(--background))",
  panelForeground: "var(--sidebar-foreground, var(--foreground))",
  muted: "var(--muted)",
  mutedForeground: "var(--muted-foreground)",
  popover: "var(--popover)",
  popoverForeground: "var(--popover-foreground)",
  border: "var(--border)",
  borderStrong: "color-mix(in srgb, var(--foreground) 18%, var(--border))",
  accent: "var(--primary)",
  accentForeground: "var(--primary-foreground)",
  aboutPrimaryForeground:
    "color-mix(in srgb, var(--ui-workspace-accent) 15%, #000)",
  selection: "color-mix(in srgb, var(--primary) 14%, transparent)",
  destructive: "var(--destructive)",
  warning: "var(--warning, #f97316)",
  focusRing: "var(--ring)",
  fontSans: "var(--font-sans, inherit)",
  fontMono: "var(--font-mono, ui-monospace, SFMono-Regular, Menlo, monospace)",
  radiusSmall: "calc(var(--radius, 0.625rem) * 0.6)",
  radiusMedium: "calc(var(--radius, 0.625rem) * 0.8)",
  radiusLarge: "var(--radius, 0.625rem)",
  shadow: "0 12px 32px rgb(15 23 42 / 24%)",
  tabHeight: "2.5rem",
  tabActiveHeight: "2.25rem",
  tabWidth: "12.5rem",
  tabMaxWidth: "20rem",
  tabCurve: "0.375rem",
  tabActiveBackground: "var(--background)",
  tabContainerBackground: "var(--sidebar, var(--ui-workspace-muted))",
  tabDivider: "var(--border)",
  stackedShadow: "-0.5rem 0 0.5rem rgb(0 0 0 / 5%)",
  stackedPaneWidth: "43.75rem",
  sidebarHeaderHeight: "2rem",
  ribbonWidth: "3rem",
  statusHeight: "1.5rem",
  settingsHeadingSize: "1rem",
  settingsHeadingWeight: "400",
  settingsLabelSize: "0.9375rem",
  settingsDescriptionSize: "0.75rem",
  settingsNavigationRowHeight: "2rem",
  settingsNavigationActiveBackground: "var(--ui-workspace-selection)",
  settingsControlHeight: "1.875rem",
  settingsControlRadius: "0.375rem",
  settingsDialogRadius: "0.5rem",
  settingsDialogMaxWidth: "68.75rem",
  settingsDialogHeight: "85vh",
  overlayZIndex: "50",
};
