<script module lang="ts">
  // @generated by ui-generator — do not edit
  import { defineMeta } from "@storybook/addon-svelte-csf";
  import * as Field from "./index.js";
  import InputExample from "./examples/input.svelte";
  import TextareaExample from "./examples/textarea.svelte";
  import SelectExample from "./examples/select.svelte";
  import FieldsetExample from "./examples/fieldset.svelte";
  import SwitchExample from "./examples/switch.svelte";
  import ResponsiveLayoutExample from "./examples/responsive-layout.svelte";
  import ValidationAndErrorsExample from "./examples/validation-and-errors.svelte";

  const { Story } = defineMeta({
    title: "Shadcn/Forms/Field",
    component: Field.Field,
  });
</script>

<Story
  name="Input"
  exportName="Input"
  tags={["upstream-example"]}
  parameters={{
    a11y: { test: "todo" as const },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <InputExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Textarea"
  exportName="Textarea"
  tags={["upstream-example"]}
  parameters={{
    a11y: { test: "todo" as const },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <TextareaExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Select"
  exportName="Select"
  tags={["upstream-example"]}
  parameters={{
    a11y: { test: "todo" as const },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <SelectExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Fieldset"
  exportName="Fieldset"
  tags={["upstream-example"]}
  parameters={{
    a11y: { test: "todo" as const },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <FieldsetExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Switch"
  exportName="Switch"
  tags={["upstream-example"]}
  parameters={{
    a11y: { test: "todo" as const },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <SwitchExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Responsive Layout"
  exportName="ResponsiveLayout"
  tags={["upstream-example"]}
  parameters={{
    a11y: { test: "todo" as const },
    docs: {
      description: {
        story: "- **Vertical fields:** Default orientation stacks label, control, and helper textideal for mobile-first layouts.\n- **Horizontal fields:** Set `orientation=\"horizontal\"` on `Field` to align the label and control side-by-side. Pair with `Field.Content` to keep descriptions aligned.\n- **Responsive fields:** Set `orientation=\"responsive\"` for automatic column layouts inside container-aware parents. Apply `@container/field-group` classes on `Field.Group` to switch orientations at specific breakpoints.",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <ResponsiveLayoutExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Validation and Errors"
  exportName="ValidationAndErrors"
  tags={["upstream-example"]}
  parameters={{
    a11y: { test: "todo" as const },
    docs: {
      description: {
        story: "- Add `data-invalid` to `Field` to switch the entire block into an error state.\n- Add `aria-invalid` on the input itself for assistive technologies.\n- Render `FieldError` immediately after the control or inside `FieldContent` to keep error messages aligned with the field. Copy",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <ValidationAndErrorsExample />
    </div>
  {/snippet}
</Story>
