<script module lang="ts">
  // @generated by ui-generator — do not edit
  import { defineMeta } from "@storybook/addon-svelte-csf";
  import * as Field from "./index.js";
  import * as exampleSources from "./Field.example-sources.js";
  import PreviewExample from "./examples/preview.svelte";
  import InputExample from "./examples/input.svelte";
  import TextareaExample from "./examples/textarea.svelte";
  import SelectExample from "./examples/select.svelte";
  import FieldsetExample from "./examples/fieldset.svelte";
  import CheckboxExample from "./examples/checkbox.svelte";
  import SwitchExample from "./examples/switch.svelte";
  import FieldGroupExample from "./examples/field-group.svelte";
  import ResponsiveLayoutExample from "./examples/responsive-layout.svelte";

  const { Story } = defineMeta({
    title: "Shadcn/Forms/Field",
    component: Field.Field,
  });
</script>

<Story
  name="Preview"
  exportName="Preview"
  tags={["upstream-example", "visual-ready"]}
  parameters={{
    visualDelta: {
      images: ["/visual-baselines/shadcn/field/preview-chromium-darwin.png"],
      opacity: 0.5,
      colorInversion: false,
      align: "canvas",
      placement: "right",
      passThresholdPercent: 0.1,
    },
    a11y: { test: "todo" },
    docs: {
      source: {
        code: exampleSources.Preview,
        language: "html",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <PreviewExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Input"
  exportName="Input"
  tags={["upstream-example", "visual-ready"]}
  parameters={{
    visualDelta: {
      images: ["/visual-baselines/shadcn/field/input-chromium-darwin.png"],
      opacity: 0.5,
      colorInversion: false,
      align: "canvas",
      placement: "right",
      passThresholdPercent: 0.1,
    },
    a11y: { test: "todo" },
    docs: {
      source: {
        code: exampleSources.Input,
        language: "html",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <InputExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Textarea"
  exportName="Textarea"
  tags={["upstream-example", "visual-ready"]}
  parameters={{
    visualDelta: {
      images: ["/visual-baselines/shadcn/field/textarea-chromium-darwin.png"],
      opacity: 0.5,
      colorInversion: false,
      align: "canvas",
      placement: "right",
      passThresholdPercent: 0.1,
    },
    a11y: { test: "todo" },
    docs: {
      source: {
        code: exampleSources.Textarea,
        language: "html",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <TextareaExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Select"
  exportName="Select"
  tags={["upstream-example", "visual-ready"]}
  parameters={{
    visualDelta: {
      images: ["/visual-baselines/shadcn/field/select-chromium-darwin.png"],
      opacity: 0.5,
      colorInversion: false,
      align: "canvas",
      placement: "right",
      passThresholdPercent: 0.1,
    },
    a11y: { test: "todo" },
    docs: {
      source: {
        code: exampleSources.Select,
        language: "html",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <SelectExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Fieldset"
  exportName="Fieldset"
  tags={["upstream-example", "visual-ready"]}
  parameters={{
    visualDelta: {
      images: ["/visual-baselines/shadcn/field/fieldset-chromium-darwin.png"],
      opacity: 0.5,
      colorInversion: false,
      align: "canvas",
      placement: "right",
      passThresholdPercent: 0.1,
    },
    a11y: { test: "todo" },
    docs: {
      source: {
        code: exampleSources.Fieldset,
        language: "html",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <FieldsetExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Checkbox"
  exportName="Checkbox"
  tags={["upstream-example", "visual-ready"]}
  parameters={{
    visualDelta: {
      images: ["/visual-baselines/shadcn/field/checkbox-chromium-darwin.png"],
      opacity: 0.5,
      colorInversion: false,
      align: "canvas",
      placement: "right",
      passThresholdPercent: 0.1,
    },
    a11y: { test: "todo" },
    docs: {
      source: {
        code: exampleSources.Checkbox,
        language: "html",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <CheckboxExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Switch"
  exportName="Switch"
  tags={["upstream-example", "visual-ready"]}
  parameters={{
    visualDelta: {
      images: ["/visual-baselines/shadcn/field/switch-chromium-darwin.png"],
      opacity: 0.5,
      colorInversion: false,
      align: "canvas",
      placement: "right",
      passThresholdPercent: 0.1,
    },
    a11y: { test: "todo" },
    docs: {
      source: {
        code: exampleSources.Switch,
        language: "html",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <SwitchExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Field Group"
  exportName="FieldGroup"
  tags={["upstream-example", "visual-ready"]}
  parameters={{
    visualDelta: {
      images: [
        "/visual-baselines/shadcn/field/field-group-chromium-darwin.png",
      ],
      opacity: 0.5,
      colorInversion: false,
      align: "canvas",
      placement: "right",
      passThresholdPercent: 0.1,
    },
    a11y: { test: "todo" },
    docs: {
      description: {
        story:
          "Stack `Field` components with `Field.Group`. Add `Field.Separator` to divide them.",
      },
      source: {
        code: exampleSources.FieldGroup,
        language: "html",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <FieldGroupExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Responsive Layout"
  exportName="ResponsiveLayout"
  tags={["upstream-example", "visual-ready"]}
  parameters={{
    visualDelta: {
      images: [
        "/visual-baselines/shadcn/field/responsive-layout-chromium-darwin.png",
      ],
      opacity: 0.5,
      colorInversion: false,
      align: "canvas",
      placement: "right",
      passThresholdPercent: 0.1,
    },
    a11y: { test: "todo" },
    docs: {
      description: {
        story:
          '- **Vertical fields:** Default orientation stacks label, control, and helper text—ideal for mobile-first layouts.\n- **Horizontal fields:** Set `orientation="horizontal"` on `Field` to align the label and control side-by-side. Pair with `Field.Content` to keep descriptions aligned.\n- **Responsive fields:** Set `orientation="responsive"` for automatic column layouts inside container-aware parents. Apply `@container/field-group` classes on `Field.Group` to switch orientations at specific breakpoints.',
      },
      source: {
        code: exampleSources.ResponsiveLayout,
        language: "html",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <ResponsiveLayoutExample />
    </div>
  {/snippet}
</Story>
