<script module lang="ts">
  // @generated by ui-generator — do not edit
  import { defineMeta } from "@storybook/addon-svelte-csf";
  import * as HoverCard from "./index.js";
  import * as exampleSources from "./HoverCard.example-sources.js";
  import BasicExample from "./examples/basic.svelte";

  const { Story } = defineMeta({
    title: "Shadcn/Overlays/Hover Card",
    component: HoverCard.HoverCard,
  });
</script>

<Story
  name="Basic"
  exportName="Basic"
  tags={["upstream-example", "skip-visual"]}
  parameters={{
    a11y: { test: "todo" },
    docs: {
      source: {
        code: exampleSources.Basic,
        language: "tsx",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <BasicExample />
    </div>
  {/snippet}
</Story>
