// @generated by ui-generator — do not edit
export const Basic =
  '<script lang="ts">\n  import * as HoverCard from "@lapismd/design-core/shadcn/hover-card";\n</script>\n\n<HoverCard.Root>\n  <HoverCard.Trigger>Hover</HoverCard.Trigger>\n  <HoverCard.Content>\n    SvelteKit - Web development, streamlined\n  </HoverCard.Content>\n</HoverCard.Root>';
