<script module lang="ts">
  // @generated by ui-generator — do not edit
  import { defineMeta } from "@storybook/addon-svelte-csf";
  import * as Tabs from "./index.js";
  import * as exampleSources from "./Tabs.example-sources.js";
  import PreviewExample from "./examples/preview.svelte";

  const { Story } = defineMeta({
    title: "Shadcn/Disclosure/Tabs",
    component: Tabs.Tabs,
  });
</script>

<Story
  name="Preview"
  exportName="Preview"
  tags={["upstream-example", "visual-approved"]}
  parameters={{
    a11y: { test: "todo" },
    docs: {
      description: {
        story: "A set of layered sections of contentknown as tab panelsthat are displayed one at a time.\n\n[Docs](https://bits-ui.com/docs/components/tabs)\n\n[API Reference](https://bits-ui.com/docs/components/tabs#api-reference)",
      },
      source: {
        code: exampleSources.Preview,
        language: "html",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <PreviewExample />
    </div>
  {/snippet}
</Story>
