import { createHash } from "node:crypto";
import {
  existsSync,
  lstatSync,
  mkdirSync,
  readFileSync,
  realpathSync,
  statSync,
  writeFileSync,
} from "node:fs";
import path from "node:path";
import fg from "fast-glob";
import type { DocsService } from "../service.js";
import { DOCS_MCP_VERSION } from "../version.js";

export const AGENT_DOCS_START = "<!-- DOCS-MCP:START -->";
export const AGENT_DOCS_END = "<!-- DOCS-MCP:END -->";

export type DocsMcpAgent = "codex" | "cursor" | "claude";
export type DocsMcpAgentSelection = DocsMcpAgent | "all";

export type ManagedAgentDocsResult = {
  filePath: string;
  agent: DocsMcpAgent;
  changed: boolean;
  action: "written" | "removed" | "missing";
};

const TARGETS: Record<DocsMcpAgent, string> = {
  codex: "AGENTS.md",
  cursor: ".cursor/rules/docs-mcp.mdc",
  claude: "CLAUDE.md",
};

function selectedAgents(selection: DocsMcpAgentSelection): DocsMcpAgent[] {
  return selection === "all" ? ["codex", "cursor", "claude"] : [selection];
}

function nearestExistingAncestor(candidate: string): string {
  let current = candidate;
  while (!existsSync(current)) {
    const parent = path.dirname(current);
    if (parent === current) return current;
    current = parent;
  }
  return statSync(current).isDirectory() ? current : path.dirname(current);
}

export function resolveAgentDocsPath(root: string, candidate: string): string {
  const resolvedRoot = realpathSync(path.resolve(root));
  const resolved = path.resolve(resolvedRoot, candidate);
  if (
    resolved === resolvedRoot ||
    !resolved.startsWith(`${resolvedRoot}${path.sep}`)
  ) {
    throw new Error(
      `Agent docs path must remain inside project root: ${candidate}`,
    );
  }
  let current = resolvedRoot;
  for (const segment of path.relative(resolvedRoot, resolved).split(path.sep)) {
    current = path.join(current, segment);
    const stat = lstatSync(current, { throwIfNoEntry: false });
    if (!stat) break;
    if (!stat.isSymbolicLink()) continue;
    let actual: string;
    try {
      actual = realpathSync(current);
    } catch {
      throw new Error(
        `Agent docs path contains a broken symlink: ${candidate}`,
      );
    }
    if (
      actual !== resolvedRoot &&
      !actual.startsWith(`${resolvedRoot}${path.sep}`)
    ) {
      throw new Error(
        `Agent docs path resolves outside project root through a symlink: ${candidate}`,
      );
    }
  }
  const ancestor = realpathSync(nearestExistingAncestor(resolved));
  if (
    ancestor !== resolvedRoot &&
    !ancestor.startsWith(`${resolvedRoot}${path.sep}`)
  ) {
    throw new Error(
      `Agent docs path resolves outside project root through a symlink: ${candidate}`,
    );
  }
  if (existsSync(resolved)) {
    const actual = realpathSync(resolved);
    if (!actual.startsWith(`${resolvedRoot}${path.sep}`)) {
      throw new Error(
        `Agent docs path resolves outside project root through a symlink: ${candidate}`,
      );
    }
  }
  return resolved;
}

function managedFingerprint(service: DocsService): string {
  const catalog = service.getCatalog();
  return createHash("sha256")
    .update(
      JSON.stringify({
        packageVersion: DOCS_MCP_VERSION,
        provider: service.config.provider.name,
        providerVersion: service.config.provider.version ?? "unversioned",
        components: catalog.components.length,
        documents: catalog.documents.length,
        artifacts: catalog.artifacts?.length ?? 0,
        guidance: catalog.project.guidance ?? {},
      }),
    )
    .digest("hex")
    .slice(0, 16);
}

export function buildManagedAgentDocs(service: DocsService): string {
  const catalog = service.getCatalog();
  const guidance = catalog.project.guidance;
  const configPath = path
    .relative(
      service.root,
      service.configPath ?? ".storybook/docs-mcp.config.ts",
    )
    .replaceAll("\\", "/");
  const invocation = `pnpm --dir ${service.root} exec docs-mcp`;
  const lines = [
    AGENT_DOCS_START,
    "## Docs MCP (managed)",
    "",
    `Generated by \`storybook-addon-docs-mcp@${DOCS_MCP_VERSION}\` for provider \`${service.config.provider.name}@${service.config.provider.version ?? "unversioned"}\`.`,
    `Catalog: ${catalog.components.length} components, ${catalog.documents.length} guides, ${catalog.artifacts?.length ?? 0} curated artifacts. Fingerprint: \`${managedFingerprint(service)}\`.`,
    "",
    "Use intent-based discovery in this order:",
    "",
    `1. \`${invocation} search "<intent>" --config ${configPath}\``,
    `2. \`${invocation} get <exact-id> --config ${configPath}\``,
    "3. Add `--section <section-id>` for focused prose or `--format full|dense` only when needed.",
    "",
    "Prefer the Docs MCP `search` → `get` tools when configured. Use",
    "`list-all-documentation` only for exhaustive browsing or Storybook story IDs.",
    "Never invent documentation IDs, component props, or import paths.",
  ];
  if (guidance?.setup?.length) {
    lines.push(
      "",
      "### Project setup",
      "",
      ...guidance.setup.map((item) => `- ${item}`),
    );
  }
  if (guidance?.readingOrder?.length) {
    lines.push(
      "",
      "### Reading order",
      "",
      ...guidance.readingOrder.map((item, index) => `${index + 1}. ${item}`),
    );
  }
  if (guidance?.rules?.length) {
    lines.push(
      "",
      "### High-value rules",
      "",
      ...guidance.rules.map((item) => `- ${item}`),
    );
  }
  lines.push(AGENT_DOCS_END);
  return `${lines.join("\n")}\n`;
}

function managedRange(
  text: string,
): { start: number; end: number } | undefined {
  const start = text.indexOf(AGENT_DOCS_START);
  const endMarker = text.indexOf(AGENT_DOCS_END);
  if ((start === -1) !== (endMarker === -1)) {
    throw new Error(
      "Managed Docs MCP markers are incomplete; repair them before retrying.",
    );
  }
  if (start === -1) return undefined;
  const duplicateStart = text.indexOf(
    AGENT_DOCS_START,
    start + AGENT_DOCS_START.length,
  );
  const duplicateEnd = text.indexOf(
    AGENT_DOCS_END,
    endMarker + AGENT_DOCS_END.length,
  );
  if (duplicateStart !== -1 || duplicateEnd !== -1 || endMarker < start) {
    throw new Error("Managed Docs MCP markers are duplicated or out of order.");
  }
  return { start, end: endMarker + AGENT_DOCS_END.length };
}

function cursorPreamble(agent: DocsMcpAgent): string {
  return agent === "cursor"
    ? "---\ndescription: Discover and retrieve local Docs MCP catalog entries\nalwaysApply: true\n---\n\n"
    : "";
}

function upsertManagedBlock(
  filePath: string,
  agent: DocsMcpAgent,
  block: string,
): boolean {
  const existing = existsSync(filePath) ? readFileSync(filePath, "utf8") : "";
  const range = managedRange(existing);
  const next = range
    ? `${existing.slice(0, range.start)}${block.trimEnd()}${existing.slice(range.end)}`
    : `${existing || cursorPreamble(agent)}${existing && !existing.endsWith("\n\n") ? "\n" : ""}${block}`;
  if (next === existing) return false;
  mkdirSync(path.dirname(filePath), { recursive: true });
  writeFileSync(filePath, next, "utf8");
  return true;
}

function removeManagedBlock(filePath: string): boolean {
  if (!existsSync(filePath)) return false;
  const existing = readFileSync(filePath, "utf8");
  const range = managedRange(existing);
  if (!range) return false;
  const next = `${existing.slice(0, range.start)}${existing.slice(range.end)}`;
  writeFileSync(filePath, next, "utf8");
  return true;
}

function targetEntries(options: {
  root: string;
  agent: DocsMcpAgentSelection;
  agentDocsPath?: string;
}): Array<{ agent: DocsMcpAgent; filePath: string }> {
  if (options.agentDocsPath) {
    const agent = options.agent === "all" ? "codex" : options.agent;
    return [
      {
        agent,
        filePath: resolveAgentDocsPath(options.root, options.agentDocsPath),
      },
    ];
  }
  return selectedAgents(options.agent).map((agent) => ({
    agent,
    filePath: resolveAgentDocsPath(options.root, TARGETS[agent]),
  }));
}

export function writeManagedAgentDocs(options: {
  service: DocsService;
  agent?: DocsMcpAgentSelection;
  agentDocsPath?: string;
}): ManagedAgentDocsResult[] {
  const block = buildManagedAgentDocs(options.service);
  return targetEntries({
    root: options.service.root,
    agent: options.agent ?? "codex",
    agentDocsPath: options.agentDocsPath,
  }).map(({ agent, filePath }) => ({
    filePath,
    agent,
    changed: upsertManagedBlock(filePath, agent, block),
    action: "written",
  }));
}

export function removeManagedAgentDocs(options: {
  root: string;
  agent?: DocsMcpAgentSelection;
  agentDocsPath?: string;
}): ManagedAgentDocsResult[] {
  return targetEntries({
    root: options.root,
    agent: options.agent ?? "codex",
    agentDocsPath: options.agentDocsPath,
  }).map(({ agent, filePath }) => {
    const changed = removeManagedBlock(filePath);
    return {
      filePath,
      agent,
      changed,
      action: changed ? "removed" : "missing",
    };
  });
}

export function inspectManagedAgentDocs(service: DocsService): Array<{
  filePath: string;
  status: "current" | "stale" | "invalid";
  message?: string;
}> {
  const expected = buildManagedAgentDocs(service).trimEnd();
  const results: Array<{
    filePath: string;
    status: "current" | "stale" | "invalid";
    message?: string;
  }> = [];
  const candidates = new Set([
    ...selectedAgents("all").map((agent) =>
      resolveAgentDocsPath(service.root, TARGETS[agent]),
    ),
    ...fg.sync(["**/*.md", "**/*.mdc"], {
      cwd: service.root,
      absolute: true,
      onlyFiles: true,
      unique: true,
      ignore: [
        "**/node_modules/**",
        "**/.git/**",
        "**/.jj/**",
        "**/.cache/**",
        "**/dist/**",
        "**/build/**",
        "**/storybook-static/**",
      ],
    }),
  ]);
  for (const filePath of candidates) {
    if (!existsSync(filePath)) continue;
    try {
      const text = readFileSync(filePath, "utf8");
      const range = managedRange(text);
      if (!range) continue;
      const current = text.slice(range.start, range.end).trimEnd();
      results.push({
        filePath,
        status: current === expected ? "current" : "stale",
      });
    } catch (error) {
      results.push({
        filePath,
        status: "invalid",
        message: error instanceof Error ? error.message : String(error),
      });
    }
  }
  return results;
}
