<script lang="ts">
  // @generated by ui-generator — do not edit

	import { Button } from "../../button/index.js";
	import { Textarea } from "../index.js";
</script>

<div class="grid w-full gap-2">
	<Textarea placeholder="Type your message here." />
	<Button>Send message</Button>
</div>
