<script lang="ts">
  // @generated by ui-generator — do not edit

  import { Label } from "../../label/index.js";
  import { Textarea } from "../index.js";
</script>

<div class="grid w-full gap-1.5">
  <Label for="message">Your message</Label>
  <Textarea placeholder="Type your message here." id="message" />
</div>
