<script module lang="ts">
  // @generated by ui-generator — do not edit
  import { defineMeta } from "@storybook/addon-svelte-csf";
  import * as Spinner from "./index.js";
  import SizeExample from "./examples/size.svelte";
  import ColorExample from "./examples/color.svelte";
  import ButtonExample from "./examples/button.svelte";
  import BadgeExample from "./examples/badge.svelte";
  import InputGroupExample from "./examples/input-group.svelte";
  import EmptyExample from "./examples/empty.svelte";
  import CustomizationExample from "./examples/customization.svelte";

  const { Story } = defineMeta({
    title: "Shadcn/Feedback/Spinner",
    // Prefer the Pascal alias (every family exports it); Root is absent on some simpleRoot barrels.
    component: Spinner.Spinner,
  });
</script>

<Story
  name="Size"
  exportName="Size"
  tags={["upstream-example"]}
  parameters={{
    a11y: { test: "todo" as const },
    docs: {
      description: {
        story: "Use the `size-*` utility class to change the size of the spinner.",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <SizeExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Color"
  exportName="Color"
  tags={["upstream-example"]}
  parameters={{
    a11y: { test: "todo" as const },
    docs: {
      description: {
        story: "Use the `text-*` utility class to change the color of the spinner.",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <ColorExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Button"
  exportName="Button"
  tags={["upstream-example"]}
  parameters={{
    a11y: { test: "todo" as const },
    docs: {
      description: {
        story: "Add a spinner to a button to indicate a loading state. The `<Button />` will handle the spacing between the spinner and the text.",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <ButtonExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Badge"
  exportName="Badge"
  tags={["upstream-example"]}
  parameters={{
    a11y: { test: "todo" as const },
    docs: {
      description: {
        story: "You can also use a spinner inside a badge.",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <BadgeExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Input Group"
  exportName="InputGroup"
  tags={["upstream-example"]}
  parameters={{
    a11y: { test: "todo" as const },
    docs: {
      description: {
        story: "Input Group can have spinners inside `<InputGroup.Addon>`.",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <InputGroupExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Empty"
  exportName="Empty"
  tags={["upstream-example"]}
  parameters={{
    a11y: { test: "todo" as const },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <EmptyExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Customization"
  exportName="Customization"
  tags={["upstream-example"]}
  parameters={{
    a11y: { test: "todo" as const },
    docs: {
      description: {
        story: "You can replace the default spinner icon with any other icon by editing the `Spinner` component.",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <CustomizationExample />
    </div>
  {/snippet}
</Story>
