<script module lang="ts">
  // @generated by ui-generator — do not edit
  import { defineMeta } from "@storybook/addon-svelte-csf";
  import * as Spinner from "./index.js";
  import * as exampleSources from "./Spinner.example-sources.js";
  import CustomizationExample from "./examples/customization.svelte";
  import SizeExample from "./examples/size.svelte";
  import ColorExample from "./examples/color.svelte";
  import ButtonExample from "./examples/button.svelte";
  import BadgeExample from "./examples/badge.svelte";
  import InputGroupExample from "./examples/input-group.svelte";
  import EmptyExample from "./examples/empty.svelte";

  const { Story } = defineMeta({
    title: "Shadcn/Feedback/Spinner",
    component: Spinner.Spinner,
  });
</script>

<Story
  name="Customization"
  exportName="Customization"
  tags={["upstream-example", "visual-approved"]}
  parameters={{
    visualDelta: {
      images: ["/visual-baselines/shadcn/spinner/customization-chromium.png"],
      opacity: 0.5,
      colorInversion: false,
      align: "canvas",
      placement: "right",
    },
    a11y: { test: "todo" },
    docs: {
      description: {
        story:
          "You can replace the default spinner icon with any other icon by editing the `Spinner` component.",
      },
      source: {
        code: exampleSources.Customization,
        language: "html",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <CustomizationExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Size"
  exportName="Size"
  tags={["upstream-example", "visual-approved"]}
  parameters={{
    visualDelta: {
      images: ["/visual-baselines/shadcn/spinner/size-chromium.png"],
      opacity: 0.5,
      colorInversion: false,
      align: "canvas",
      placement: "right",
    },
    a11y: { test: "todo" },
    docs: {
      description: {
        story:
          "Use the `size-*` utility class to change the size of the spinner.",
      },
      source: {
        code: exampleSources.Size,
        language: "html",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <SizeExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Color"
  exportName="Color"
  tags={["upstream-example", "visual-approved"]}
  parameters={{
    visualDelta: {
      images: ["/visual-baselines/shadcn/spinner/color-chromium.png"],
      opacity: 0.5,
      colorInversion: false,
      align: "canvas",
      placement: "right",
    },
    a11y: { test: "todo" },
    docs: {
      description: {
        story:
          "Use the `text-*` utility class to change the color of the spinner.",
      },
      source: {
        code: exampleSources.Color,
        language: "html",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <ColorExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Button"
  exportName="Button"
  tags={["upstream-example", "visual-approved"]}
  parameters={{
    visualDelta: {
      images: ["/visual-baselines/shadcn/spinner/button-chromium.png"],
      opacity: 0.5,
      colorInversion: false,
      align: "canvas",
      placement: "right",
    },
    a11y: { test: "todo" },
    docs: {
      description: {
        story:
          "Add a spinner to a button to indicate a loading state. The `` will handle the spacing between the spinner and the text.",
      },
      source: {
        code: exampleSources.Button,
        language: "html",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <ButtonExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Badge"
  exportName="Badge"
  tags={["upstream-example", "visual-approved"]}
  parameters={{
    visualDelta: {
      images: ["/visual-baselines/shadcn/spinner/badge-chromium.png"],
      opacity: 0.5,
      colorInversion: false,
      align: "canvas",
      placement: "right",
    },
    a11y: { test: "todo" },
    docs: {
      description: {
        story: "You can also use a spinner inside a badge.",
      },
      source: {
        code: exampleSources.Badge,
        language: "html",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <BadgeExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Input Group"
  exportName="InputGroup"
  tags={["upstream-example", "visual-approved"]}
  parameters={{
    visualDelta: {
      images: ["/visual-baselines/shadcn/spinner/input-group-chromium.png"],
      opacity: 0.5,
      colorInversion: false,
      align: "canvas",
      placement: "right",
    },
    a11y: { test: "todo" },
    docs: {
      description: {
        story: "Input Group can have spinners inside `InputGroup.Addon`.",
      },
      source: {
        code: exampleSources.InputGroup,
        language: "html",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <InputGroupExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Empty"
  exportName="Empty"
  tags={["upstream-example", "visual-approved"]}
  parameters={{
    visualDelta: {
      images: ["/visual-baselines/shadcn/spinner/empty-chromium.png"],
      opacity: 0.5,
      colorInversion: false,
      align: "canvas",
      placement: "right",
    },
    a11y: { test: "todo" },
    docs: {
      source: {
        code: exampleSources.Empty,
        language: "html",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <EmptyExample />
    </div>
  {/snippet}
</Story>
