<script module lang="ts">
  // @generated by ui-generator — do not edit
  import { defineMeta } from "@storybook/addon-svelte-csf";
  import * as Separator from "./index.js";
  import * as exampleSources from "./Separator.example-sources.js";
  import PreviewExample from "./examples/preview.svelte";

  const { Story } = defineMeta({
    title: "Shadcn/Layout/Separator",
    component: Separator.Separator,
  });
</script>

<Story
  name="Preview"
  exportName="Preview"
  tags={["upstream-example", "visual-approved"]}
  parameters={{
    a11y: { test: "todo" },
    docs: {
      description: {
        story: "Visually or semantically separates content.\n\n[Docs](https://bits-ui.com/docs/components/separator)\n\n[API Reference](https://bits-ui.com/docs/components/separator#api-reference)",
      },
      source: {
        code: exampleSources.Preview,
        language: "html",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <PreviewExample />
    </div>
  {/snippet}
</Story>
