import {
  defineConfig,
  headingRequirements,
  singleIdVerification,
} from "@lapismd/spec-validator";

const shadcnChapters = {
  accordion: ["spec/src/shadcn/disclosure-and-navigation.md"],
  alert: ["spec/src/shadcn/data-and-feedback.md"],
  "alert-dialog": ["spec/src/shadcn/overlays.md"],
  badge: ["spec/src/shadcn/data-and-feedback.md"],
  breadcrumb: ["spec/src/shadcn/disclosure-and-navigation.md"],
  button: ["spec/src/shadcn/actions-and-content.md"],
  "button-group": ["spec/src/shadcn/actions-and-content.md"],
  card: ["spec/src/shadcn/layout.md"],
  checkbox: ["spec/src/shadcn/forms.md"],
  code: ["spec/src/shadcn/actions-and-content.md"],
  "code-block": ["spec/src/shadcn/actions-and-content.md"],
  collapsible: ["spec/src/shadcn/disclosure-and-navigation.md"],
  "column-canvas": ["spec/src/shadcn/layout.md"],
  command: ["spec/src/shadcn/forms.md"],
  "command-view": ["spec/src/shadcn/forms.md"],
  "context-menu": ["spec/src/shadcn/overlays.md"],
  dialog: ["spec/src/shadcn/overlays.md"],
  drawer: ["spec/src/shadcn/overlays.md"],
  "dropdown-menu": ["spec/src/shadcn/overlays.md"],
  empty: ["spec/src/shadcn/data-and-feedback.md"],
  field: ["spec/src/shadcn/forms.md"],
  "hover-card": ["spec/src/shadcn/overlays.md"],
  input: ["spec/src/shadcn/forms.md"],
  "input-group": ["spec/src/shadcn/forms.md"],
  label: ["spec/src/shadcn/forms.md"],
  pagination: ["spec/src/shadcn/disclosure-and-navigation.md"],
  popover: ["spec/src/shadcn/overlays.md"],
  progress: ["spec/src/shadcn/data-and-feedback.md"],
  resizable: ["spec/src/shadcn/layout.md"],
  "scroll-area": ["spec/src/shadcn/layout.md"],
  select: ["spec/src/shadcn/forms.md"],
  separator: ["spec/src/shadcn/layout.md"],
  sheet: ["spec/src/shadcn/overlays.md"],
  sidebar: ["spec/src/shadcn/layout.md"],
  skeleton: ["spec/src/shadcn/data-and-feedback.md"],
  slider: ["spec/src/shadcn/forms.md"],
  spinner: ["spec/src/shadcn/data-and-feedback.md"],
  "swipe-item": ["spec/src/shadcn/actions-and-content.md"],
  switch: ["spec/src/shadcn/forms.md"],
  table: ["spec/src/shadcn/data-and-feedback.md"],
  tabs: ["spec/src/shadcn/disclosure-and-navigation.md"],
  textarea: ["spec/src/shadcn/forms.md"],
  toggle: ["spec/src/shadcn/actions-and-content.md"],
  "toggle-group": ["spec/src/shadcn/actions-and-content.md"],
  tooltip: ["spec/src/shadcn/overlays.md"],
};

const formChapters = {
  core: ["spec/src/forms/core-and-orchestrators.md"],
  "structured-form": ["spec/src/forms/core-and-orchestrators.md"],
  "yaml-backed-form": ["spec/src/forms/core-and-orchestrators.md"],
  "json-backed-form": ["spec/src/forms/core-and-orchestrators.md"],
  "patchable-form": ["spec/src/forms/core-and-orchestrators.md"],
  "autocomplete-input": ["spec/src/forms/inputs.md"],
  "chip-autocomplete": ["spec/src/forms/inputs.md"],
  "color-picker": ["spec/src/forms/inputs.md"],
  "cycle-picker": ["spec/src/forms/inputs.md"],
  "date-picker": ["spec/src/forms/inputs.md"],
  "filter-command-picker": ["spec/src/forms/inputs.md"],
  "inline-option-picker": ["spec/src/forms/inputs.md"],
  "list-editor": ["spec/src/forms/inputs.md"],
  "password-input": ["spec/src/forms/inputs.md"],
  "reference-picker": ["spec/src/forms/inputs.md"],
  "secret-field": ["spec/src/forms/inputs.md"],
  "segmented-control": ["spec/src/forms/inputs.md"],
  "task-due-calendar": ["spec/src/forms/inputs.md"],
  "time-picker": ["spec/src/forms/inputs.md"],
  "search-filter-in-form": ["spec/src/forms/inputs.md"],
  "add-section-chooser": ["spec/src/forms/layout.md"],
  "collapsible-item-list": ["spec/src/forms/layout.md"],
  "entry-actions": ["spec/src/forms/layout.md"],
  "form-add-button": ["spec/src/forms/layout.md"],
  "form-control-row": ["spec/src/forms/layout.md"],
  "form-field": ["spec/src/forms/layout.md"],
  "form-placeholder": ["spec/src/forms/layout.md"],
  "form-section-header": ["spec/src/forms/layout.md"],
  "form-sheet": ["spec/src/forms/layout.md"],
  "form-toolbar": ["spec/src/forms/layout.md"],
  "sortable-array-item": ["spec/src/forms/layout.md"],
  "code-editor": ["spec/src/forms/editors.md"],
  "code-highlighter": ["spec/src/forms/editors.md"],
  "yaml-editor": ["spec/src/forms/editors.md"],
  "form-review": ["spec/src/forms/review.md"],
  "field-review-actions": ["spec/src/forms/review.md"],
  "unified-review-diff": ["spec/src/forms/review.md"],
  "complete-cv-form": ["spec/src/forms/examples.md"],
};

export default defineConfig(headingRequirements(), {
  name: "design-core",
  idPattern: /^DC-[A-Z]+-\d{3}$/,
  ruleIds: {
    summary: "DC-GOV-003",
    governance: "DC-GOV-001",
    verification: "DC-GOV-002",
    book: "DC-GOV-003",
    bookIgnore: "DC-GOV-008",
    publicSurfaces: "DC-GOV-003",
    storybookCatalog: "DC-GOV-009",
    storybookMirrors: "DC-CAT-005",
    qmd: "DC-GOV-005",
    specFirst: "DC-GOV-004",
    internal: "DC-GOV-003",
  },
  diagnostics: {
    "SPEC-DETAILS-*": "DC-GOV-003",
    "SPEC-REQ-UNKNOWN": "DC-GOV-003",
    "SPEC-STORY-SOURCE-FIELDS": "DC-CAT-007",
    "SPEC-STORY-SYNTAX-LANGUAGE": "DC-CAT-008",
    "SPEC-STORY-SOURCE-BOUNDARY": "DC-CAT-006",
    "SPEC-STORY-SOURCE-MISSING": "DC-GOV-009",
  },
  validators: {
    summary: true,
    governance: {
      extras: ["AGENTS.md", "README.md"],
    },
    verification: singleIdVerification(),
    book: true,
    publicSurfaces: {
      map: "spec/public-surfaces.json",
      roots: ["src"],
      requireCoverage: true,
    },
    storybookCatalog: {
      roots: ["src"],
      packageName: "@lapismd/design-core",
    },
    storybookMirrors: {
      style: "src-spec-mdx",
      directory: "src/spec",
      titlePrefix: "Specification",
      verifyTarget: true,
      verifyTitle: true,
      verifyContent: true,
      previewPath: ".storybook/preview.ts",
      verifyOrder: true,
    },
    qmd: { collection: "design-core-spec" },
    specFirst: {
      mode: "mapped",
      canonicalPattern: "^spec/src/(?!SUMMARY\\.md$).+\\.md$",
      ignore: [
        "(^|/)node_modules/",
        "(^|/)(?:dist|build|\\.svelte-kit|\\.turbo)/",
        "(^|/)(?:coverage|test-results|playwright-report|storybook-static(?:-check)?)/",
        "^spec/book/",
        "\\.(?:spec|test)\\.[cm]?[jt]sx?$",
        "\\.stories\\.(?:svelte|[cm]?[jt]sx?)$",
        "\\.example-sources\\.[cm]?[jt]sx?$",
        "\\.mdx$",
        "^README\\.md$",
      ],
      rules: [
        {
          pattern: "^src/spec/.*\\.mdx$",
          chapters: ["spec/src/storybook-catalog.md"],
        },
        {
          pattern: "^src/shared/shadcn/([^/]+)/",
          captureMap: shadcnChapters,
        },
        {
          pattern: "^src/shared/forms/([^/]+)/",
          captureMap: formChapters,
        },
        {
          pattern: "^src/shared/forms/[^/]+$",
          chapters: ["spec/src/forms/core-and-orchestrators.md"],
        },
        {
          pattern: "^(?:src/(?:styles|theme|storybook)\\.css|src/themes/)",
          chapters: ["spec/src/styling-and-themes.md"],
        },
        { pattern: "^src/shared/filter/", chapters: ["spec/src/filter.md"] },
        { pattern: "^src/shared/ai/", chapters: ["spec/src/ai.md"] },
        { pattern: "^src/shared/diff/", chapters: ["spec/src/diff.md"] },
        { pattern: "^src/shared/shell/", chapters: ["spec/src/shell.md"] },
        {
          pattern:
            "^src/shared/workspace/(app-shell|core|demo|drag|view-host)(?:/|$)",
          chapters: ["spec/src/workspace/framework.md"],
        },
        {
          pattern: "^src/shared/workspace/(explorer|problems)(?:/|$)",
          chapters: ["spec/src/workspace/panels.md"],
        },
        {
          pattern: "^src/shared/workspace/(plugins)(?:/|$)",
          chapters: ["spec/src/workspace/plugins.md"],
        },
        {
          pattern: "^src/shared/workspace/[^/]+$",
          chapters: ["spec/src/workspace/framework.md"],
        },
        {
          pattern:
            "^src/shared/workspace/(?!(?:app-shell|core|demo|drag|view-host|explorer|problems|plugins)(?:/|$))[^/]+/",
          chapters: ["spec/src/workspace/components.md"],
        },
        {
          pattern: "^\\.storybook/",
          chapters: ["spec/src/storybook-catalog.md"],
        },
        {
          pattern: "^packages/storybook-addon-docs-mcp/",
          chapters: ["spec/src/tooling.md"],
        },
        {
          pattern:
            "^(?:scripts/spec-validation/|\\.qmd/index\\.ya?ml$|\\.gitignore$|spec/book\\.toml$|spec/public-surfaces\\.json$|spec-validator\\.config\\.mjs$)",
          chapters: ["spec/src/spec-governance.md"],
        },
        {
          pattern: "^(?:docs/agent/|AGENTS\\.md$)",
          chapters: ["spec/src/spec-governance.md", "spec/src/tooling.md"],
        },
        {
          pattern: "^scripts/(?!spec-validation/)",
          chapters: ["spec/src/tooling.md"],
        },
        {
          pattern:
            "^(?:package\\.json|pnpm-lock\\.yaml|pnpm-workspace\\.yaml)$",
          chapters: ["spec/src/architecture.md", "spec/src/packages.md"],
        },
        {
          pattern:
            "^(?:svelte|vite|vitest|playwright|tsconfig)(?:\\.[^.]+)*\\.(?:js|mjs|ts|json)$",
          chapters: ["spec/src/architecture.md", "spec/src/tooling.md"],
        },
      ],
      protected: [
        "^(?:src/shared/|src/(?:styles|theme|storybook)\\.css$|src/themes/|src/spec/|\\.storybook/|scripts/|packages/[^/]+/src/|docs/agent/|AGENTS\\.md$|spec/(?:book\\.toml|public-surfaces\\.json)$|spec-validator\\.config\\.mjs$|package\\.json$|pnpm-lock\\.yaml$|pnpm-workspace\\.yaml$|svelte\\.|vite\\.|vitest\\.|playwright\\.|tsconfig)",
      ],
    },
  },
});
