<script lang="ts">
  // @generated by ui-generator — do not edit

  import { buttonVariants } from "../../button/index.js";
  import * as Tooltip from "../index.js";
</script>

<Tooltip.Provider>
  <div class="flex flex-wrap items-center gap-4">
    <Tooltip.Root>
      <Tooltip.Trigger class={buttonVariants({ variant: "outline" })}>
        Default delay
      </Tooltip.Trigger>
      <Tooltip.Content>
        <p>Uses the outer provider delay</p>
      </Tooltip.Content>
    </Tooltip.Root>

    <Tooltip.Provider delayDuration={0}>
      <Tooltip.Root>
        <Tooltip.Trigger class={buttonVariants({ variant: "outline" })}>
          Instant
        </Tooltip.Trigger>
        <Tooltip.Content>
          <p>Closest provider wins (delayDuration=0)</p>
        </Tooltip.Content>
      </Tooltip.Root>
    </Tooltip.Provider>
  </div>
</Tooltip.Provider>
