<script lang="ts">
  // @generated by ui-generator — do not edit

  import Search from "@lucide/svelte/icons/search";
  import { Button } from "../../button/index.js";
  import * as ButtonGroup from "../index.js";
  import { Input } from "../../input/index.js";
</script>

<ButtonGroup.Root>
  <Input placeholder="Search..." />
  <Button variant="outline" size="icon" aria-label="Search">
    <Search />
  </Button>
</ButtonGroup.Root>
