<script lang="ts">
  // @generated by ui-generator — do not edit

  import { Button } from "../../button/index.js";
  import * as ButtonGroup from "../index.js";
</script>

<ButtonGroup.Root>
  <Button variant="secondary" size="sm">Copy</Button>
  <ButtonGroup.Separator />
  <Button variant="secondary" size="sm">Paste</Button>
</ButtonGroup.Root>
