<script lang="ts">
  // @generated by ui-generator — do not edit

  import Plus from "@lucide/svelte/icons/plus";
  import { Button } from "../../button/index.js";
  import * as ButtonGroup from "../index.js";
</script>

<ButtonGroup.Root>
  <Button variant="secondary">Button</Button>
  <ButtonGroup.Separator />
  <Button variant="secondary" size="icon">
    <Plus />
  </Button>
</ButtonGroup.Root>
