<script lang="ts">
  // @generated by ui-generator — do not edit

  import ArrowUpIcon from "@lucide/svelte/icons/arrow-up";
  import { Button } from "../index.js";
</script>
<div class="flex flex-col gap-8">
  <Button variant="outline" size="icon" class="rounded-full">
    <ArrowUpIcon />
  </Button>
</div>
