<script lang="ts">
  // @generated by ui-generator — do not edit

  import { Button } from "../index.js";
  import { Spinner } from "../../spinner/index.js";
</script>

<Button size="sm" variant="outline" disabled>
  <Spinner />
  Submit
</Button>
