<script lang="ts">
  // @generated by ui-generator — do not edit

	import IconGitBranch from "@lucide/svelte/icons/git-branch";
	import { Button } from "../index.js";
</script>

<Button variant="outline" size="sm">
	<IconGitBranch /> New Branch
</Button>
