<script module lang="ts">
  // @generated by ui-generator — do not edit
  import { defineMeta } from "@storybook/addon-svelte-csf";
  import * as Card from "./index.js";
  import * as exampleSources from "./Card.example-sources.js";
  import PreviewExample from "./examples/preview.svelte";
  import Preview2Example from "./examples/preview-2.svelte";
  import SpacingExample from "./examples/spacing.svelte";
  import Spacing2Example from "./examples/spacing-2.svelte";
  import ImageExample from "./examples/image.svelte";

  const { Story } = defineMeta({
    title: "Shadcn/Layout/Card",
    component: Card.Card,
  });
</script>

<Story
  name="Preview"
  exportName="Preview"
  tags={["upstream-example", "visual-ready"]}
  parameters={{
    visualDelta: {"images":["/visual-baselines/shadcn/card/preview-chromium-darwin.png"],"opacity":0.5,"colorInversion":false,"align":"canvas","placement":"right","passThresholdPercent":0.1},
    a11y: { test: "todo" },
    docs: {
      source: {
        code: exampleSources.Preview,
        language: "html",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <PreviewExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Preview"
  exportName="Preview2"
  tags={["upstream-example", "visual-ready"]}
  parameters={{
    visualDelta: {"images":["/visual-baselines/shadcn/card/preview-chromium-darwin.png"],"opacity":0.5,"colorInversion":false,"align":"canvas","placement":"right","passThresholdPercent":0.1},
    a11y: { test: "todo" },
    docs: {
      source: {
        code: exampleSources.Preview2,
        language: "html",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <Preview2Example />
    </div>
  {/snippet}
</Story>

<Story
  name="Spacing"
  exportName="Spacing"
  tags={["upstream-example", "visual-ready"]}
  parameters={{
    visualDelta: {"images":["/visual-baselines/shadcn/card/spacing-chromium-darwin.png"],"opacity":0.5,"colorInversion":false,"align":"canvas","placement":"right","passThresholdPercent":0.1},
    a11y: { test: "todo" },
    docs: {
      description: {
        story:
          "In addition to the `size` prop, you can use the `--card-spacing` CSS variable to control the spacing between sections and the inset of card parts.",
      },
      source: {
        code: exampleSources.Spacing,
        language: "html",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <SpacingExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Spacing"
  exportName="Spacing2"
  tags={["upstream-example", "visual-ready"]}
  parameters={{
    visualDelta: {"images":["/visual-baselines/shadcn/card/spacing-chromium-darwin.png"],"opacity":0.5,"colorInversion":false,"align":"canvas","placement":"right","passThresholdPercent":0.1},
    a11y: { test: "todo" },
    docs: {
      description: {
        story:
          'ComponentPreview name="card-spacing" class="[&_.preview]:h-[34rem]">\n\nUse negative margins with `-mx-(--card-spacing)` to make content go edge to edge while keeping it aligned with the card inset. When the edge-to-edge content sits above a footer, use `-mb-(--card-spacing)` on `CardContent` to remove the section gap.',
      },
      source: {
        code: exampleSources.Spacing2,
        language: "html",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <Spacing2Example />
    </div>
  {/snippet}
</Story>

<Story
  name="Image"
  exportName="Image"
  tags={["upstream-example", "visual-ready"]}
  parameters={{
    visualDelta: {"images":["/visual-baselines/shadcn/card/image-chromium-darwin.png"],"opacity":0.5,"colorInversion":false,"align":"canvas","placement":"right","passThresholdPercent":0.1},
    a11y: { test: "todo" },
    docs: {
      description: {
        story:
          "Add an image before the card header to create a card with an image.",
      },
      source: {
        code: exampleSources.Image,
        language: "html",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <ImageExample />
    </div>
  {/snippet}
</Story>
