<script module lang="ts">
  // @generated by ui-generator — do not edit
  import { defineMeta } from "@storybook/addon-svelte-csf";
  import * as Card from "./index.js";
  import * as exampleSources from "./Card.example-sources.js";
  import PreviewExample from "./examples/preview.svelte";
  import SpacingExample from "./examples/spacing.svelte";
  import ImageExample from "./examples/image.svelte";

  const { Story } = defineMeta({
    title: "Shadcn/Layout/Card",
    component: Card.Card,
  });
</script>

<Story
  name="Preview"
  exportName="Preview"
  tags={["upstream-example"]}
  parameters={{
    a11y: { test: "todo" },
    docs: {
      description: {
        story: "Displays a card with header, content, and footer.",
      },
      source: {
        code: exampleSources.Preview,
        language: "html",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <PreviewExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Spacing"
  exportName="Spacing"
  tags={["upstream-example"]}
  parameters={{
    a11y: { test: "todo" },
    docs: {
      description: {
        story: "In addition to the `size` prop, you can use the `--card-spacing` CSS variable to control the spacing between sections and the inset of card parts.",
      },
      source: {
        code: exampleSources.Spacing,
        language: "html",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <SpacingExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Image"
  exportName="Image"
  tags={["upstream-example"]}
  parameters={{
    a11y: { test: "todo" },
    docs: {
      description: {
        story: "Add an image before the card header to create a card with an image.",
      },
      source: {
        code: exampleSources.Image,
        language: "html",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <ImageExample />
    </div>
  {/snippet}
</Story>
