export const Basic =
  '<script lang="ts">\n\timport * as ColumnCanvas from "@lapismd/design-core/shadcn/column-canvas";\n\n\tconst canvas = ColumnCanvas.createColumnCanvasController({\n\t\tcolumns: {\n\t\t\tcategories: { defaultWidth: 260, collapsible: true },\n\t\t\titems: { defaultWidth: 300, collapsible: true },\n\t\t},\n\t});\n\n\tconst categories = [\n\t\t{ id: "design", label: "Design" },\n\t\t{ id: "engineering", label: "Engineering" },\n\t];\n\tconst items = {\n\t\tdesign: [\n\t\t\t{ id: "tokens", label: "Tokens" },\n\t\t\t{ id: "components", label: "Components" },\n\t\t],\n\t\tengineering: [\n\t\t\t{ id: "api", label: "API" },\n\t\t\t{ id: "ci", label: "CI" },\n\t\t],\n\t} as const;\n</script>\n\n<div style="height: 360px">\n\t<ColumnCanvas.Root controller={canvas}>\n\t\t<ColumnCanvas.Column id="categories" title="Categories" count={categories.length}>\n\t\t\t<ColumnCanvas.Body>\n\t\t\t\t{#each categories as category (category.id)}\n\t\t\t\t\t<ColumnCanvas.Item\n\t\t\t\t\t\tselected={canvas.isSelected(0, category.id)}\n\t\t\t\t\t\tonclick={() => canvas.select(0, category.id)}\n\t\t\t\t\t>\n\t\t\t\t\t\t{category.label}\n\t\t\t\t\t</ColumnCanvas.Item>\n\t\t\t\t{/each}\n\t\t\t</ColumnCanvas.Body>\n\t\t</ColumnCanvas.Column>\n\n\t\t{#if canvas.path[0]}\n\t\t\t<ColumnCanvas.Column\n\t\t\t\tid="items"\n\t\t\t\ttitle="Items"\n\t\t\t\tcount={items[canvas.path[0]].length}\n\t\t\t>\n\t\t\t\t<ColumnCanvas.Body>\n\t\t\t\t\t{#each items[canvas.path[0]] as item (item.id)}\n\t\t\t\t\t\t<ColumnCanvas.Item>{item.label}</ColumnCanvas.Item>\n\t\t\t\t\t{/each}\n\t\t\t\t</ColumnCanvas.Body>\n\t\t\t</ColumnCanvas.Column>\n\t\t{/if}\n\t</ColumnCanvas.Root>\n</div>';

export const ThreeLevel =
  '<script lang="ts">\n\timport * as ColumnCanvas from "@lapismd/design-core/shadcn/column-canvas";\n\n\tconst canvas = ColumnCanvas.createColumnCanvasController({\n\t\tcolumns: {\n\t\t\tgroups: { defaultWidth: 240, collapsible: true },\n\t\t\titems: { defaultWidth: 280, collapsible: true },\n\t\t\tdetail: { defaultWidth: 320 },\n\t\t},\n\t});\n\n\tconst groups = [\n\t\t{\n\t\t\tid: "product",\n\t\t\tlabel: "Product",\n\t\t\titems: [\n\t\t\t\t{ id: "roadmap", label: "Roadmap", detail: "Q3 milestones and owners." },\n\t\t\t\t{ id: "launch", label: "Launch", detail: "Go-to-market checklist." },\n\t\t\t],\n\t\t},\n\t\t{\n\t\t\tid: "platform",\n\t\t\tlabel: "Platform",\n\t\t\titems: [\n\t\t\t\t{ id: "auth", label: "Auth", detail: "Session and SSO work." },\n\t\t\t\t{ id: "billing", label: "Billing", detail: "Invoice pipeline status." },\n\t\t\t],\n\t\t},\n\t];\n\n\tconst selectedGroup = $derived(groups.find((group) => group.id === canvas.path[0]));\n\tconst selectedItem = $derived(\n\t\tselectedGroup?.items.find((item) => item.id === canvas.path[1]),\n\t);\n</script>\n\n<div style="height: 400px">\n\t<ColumnCanvas.Root controller={canvas}>\n\t\t<ColumnCanvas.Column id="groups" title="Groups" count={groups.length}>\n\t\t\t<ColumnCanvas.Body>\n\t\t\t\t{#each groups as group (group.id)}\n\t\t\t\t\t<ColumnCanvas.Item\n\t\t\t\t\t\tselected={canvas.isSelected(0, group.id)}\n\t\t\t\t\t\tonclick={() => canvas.select(0, group.id)}\n\t\t\t\t\t>\n\t\t\t\t\t\t{group.label}\n\t\t\t\t\t</ColumnCanvas.Item>\n\t\t\t\t{/each}\n\t\t\t</ColumnCanvas.Body>\n\t\t</ColumnCanvas.Column>\n\n\t\t{#if selectedGroup}\n\t\t\t<ColumnCanvas.Column id="items" title={selectedGroup.label} count={selectedGroup.items.length}>\n\t\t\t\t<ColumnCanvas.Body>\n\t\t\t\t\t{#each selectedGroup.items as item (item.id)}\n\t\t\t\t\t\t<ColumnCanvas.Item\n\t\t\t\t\t\t\tselected={canvas.isSelected(1, item.id)}\n\t\t\t\t\t\t\tonclick={() => canvas.select(1, item.id)}\n\t\t\t\t\t\t>\n\t\t\t\t\t\t\t{item.label}\n\t\t\t\t\t\t</ColumnCanvas.Item>\n\t\t\t\t\t{/each}\n\t\t\t\t</ColumnCanvas.Body>\n\t\t\t</ColumnCanvas.Column>\n\t\t{/if}\n\n\t\t{#if selectedItem}\n\t\t\t<ColumnCanvas.Column id="detail" title={selectedItem.label}>\n\t\t\t\t<ColumnCanvas.Body>\n\t\t\t\t\t<p>{selectedItem.detail}</p>\n\t\t\t\t</ColumnCanvas.Body>\n\t\t\t</ColumnCanvas.Column>\n\t\t{/if}\n\t</ColumnCanvas.Root>\n</div>';

export const CollapseAndExpand =
  '<script lang="ts">\n\timport * as ColumnCanvas from "@lapismd/design-core/shadcn/column-canvas";\n\n\tconst canvas = ColumnCanvas.createColumnCanvasController({\n\t\tcolumns: {\n\t\t\trefs: {\n\t\t\t\tdefaultWidth: 280,\n\t\t\t\tcollapsible: true,\n\t\t\t},\n\t\t},\n\t});\n</script>\n\n<div style="height: 320px">\n\t<ColumnCanvas.Root controller={canvas}>\n\t\t<ColumnCanvas.Column id="refs" title="Branches" count={2}>\n\t\t\t<ColumnCanvas.Body>\n\t\t\t\t<ColumnCanvas.Item>main</ColumnCanvas.Item>\n\t\t\t\t<ColumnCanvas.Item>feature/canvas</ColumnCanvas.Item>\n\t\t\t</ColumnCanvas.Body>\n\t\t</ColumnCanvas.Column>\n\t</ColumnCanvas.Root>\n</div>';

export const Resizable =
  '<script lang="ts">\n\timport * as ColumnCanvas from "@lapismd/design-core/shadcn/column-canvas";\n\n\tconst canvas = ColumnCanvas.createColumnCanvasController({\n\t\tcolumns: {\n\t\t\tworkspace: {\n\t\t\t\tdefaultWidth: 280,\n\t\t\t\tminWidth: 240,\n\t\t\t\tmaxWidth: 480,\n\t\t\t\tresizable: true,\n\t\t\t},\n\t\t},\n\t});\n</script>\n\n<div style="height: 320px">\n\t<ColumnCanvas.Root controller={canvas}>\n\t\t<ColumnCanvas.Column id="workspace" title="Workspace">\n\t\t\t<ColumnCanvas.Body>\n\t\t\t\t<p>Drag the trailing edge to resize. Width: {canvas.getWidth("workspace")}px</p>\n\t\t\t</ColumnCanvas.Body>\n\t\t</ColumnCanvas.Column>\n\t</ColumnCanvas.Root>\n</div>';

export const PersistedWidths =
  '<script lang="ts">\n\timport * as ColumnCanvas from "@lapismd/design-core/shadcn/column-canvas";\n\n\tconst canvas = ColumnCanvas.createColumnCanvasController({\n\t\tcolumns: {\n\t\t\tworkspace: {\n\t\t\t\tdefaultWidth: 280,\n\t\t\t\tresizable: true,\n\t\t\t\tcollapsible: true,\n\t\t\t},\n\t\t},\n\t\tpersistence: ColumnCanvas.createLocalStorageColumnCanvasLayoutPersistence(\n\t\t\t"demo/column-canvas",\n\t\t),\n\t});\n</script>\n\n<div style="height: 320px">\n\t<ColumnCanvas.Root controller={canvas}>\n\t\t<ColumnCanvas.Column id="workspace" title="Workspace">\n\t\t\t<ColumnCanvas.Body>\n\t\t\t\t<p>Widths and collapse restore from the persistence adapter.</p>\n\t\t\t</ColumnCanvas.Body>\n\t\t</ColumnCanvas.Column>\n\t</ColumnCanvas.Root>\n</div>';
