import {
  existsSync,
  mkdirSync,
  readdirSync,
  unlinkSync,
  writeFileSync,
} from "node:fs";
import path from "node:path";
import { rewritePackageImports } from "./rewrite-example.js";
import type { UpstreamDocs } from "./types.js";
import type { RewrittenExample } from "./types.js";

function toPascalCase(kebab: string): string {
  return kebab
    .split("-")
    .map((p) => p[0]!.toUpperCase() + p.slice(1))
    .join("");
}

/** defineMeta `component` export — some families lack a Pascal alias / Root. */
function storyMetaComponentExpr(component: string, pascal: string): string {
  if (component === "resizable") return `${pascal}.PaneGroup`;
  if (component === "sidebar") return `${pascal}.Provider`;
  return `${pascal}.${pascal}`;
}

function stripSponsorAndHero(markdown: string): string {
  const lines = markdown.split("\n");
  const out: string[] = [];
  let i = 0;
  // Keep H1 + description paragraph
  if (lines[0]?.startsWith("# ")) {
    out.push(lines[0]!);
    i = 1;
    while (i < lines.length && !lines[i]!.trim()) {
      out.push("");
      i++;
    }
    while (
      i < lines.length &&
      lines[i]!.trim() &&
      !lines[i]!.startsWith("#") &&
      !lines[i]!.startsWith("```") &&
      !/Epicenter|Special Sponsor/i.test(lines[i]!)
    ) {
      out.push(lines[i]!);
      i++;
    }
    out.push("");
  }
  // Skip until ## Installation or ## Usage
  while (i < lines.length) {
    if (/^##\s+(\[)?(Installation|Usage)/i.test(lines[i]!.trim())) break;
    i++;
  }
  out.push(...lines.slice(i));
  return (
    out
      .join("\n")
      .replace(/\n*View Code\n*/g, "\n")
      .replace(/\n{3,}/g, "\n\n")
      .trim() + "\n"
  );
}

/** Drop the upstream Installation section (CLI install is not part of this catalog). */
function stripInstallationSection(markdown: string): string {
  const lines = markdown.split("\n");
  const out: string[] = [];
  let skipping = false;
  for (const line of lines) {
    if (/^##\s+(\[)?Installation\b/i.test(line.trim())) {
      skipping = true;
      continue;
    }
    if (skipping && /^##\s+/.test(line.trim())) {
      skipping = false;
    }
    if (skipping) continue;
    out.push(line);
  }
  return out.join("\n").replace(/\n{3,}/g, "\n\n").trim() + "\n";
}

/**
 * Strip example ```svelte fences (and optional View Code noise) so MDX can
 * render live Canvas blocks instead of static code.
 */
function stripExampleCodeFences(markdown: string): string {
  const examplesIdx = markdown.search(/^##\s+(\[)?Examples\b/im);
  if (examplesIdx < 0) return markdown;

  const before = markdown.slice(0, examplesIdx);
  let examples = markdown.slice(examplesIdx);
  examples = examples.replace(/```svelte\n[\s\S]*?```/g, "");
  examples = examples.replace(/\n*View Code\n*/g, "\n");
  examples = examples.replace(/\n{3,}/g, "\n\n");
  return (before + examples).trim() + "\n";
}

function rewriteDocsMarkdown(
  docs: UpstreamDocs,
  component: string,
): string {
  const md = rewritePackageImports(
    stripExampleCodeFences(
      stripInstallationSection(stripSponsorAndHero(docs.rawMarkdown)),
    ),
    component,
  );
  const banner = `<!-- Adapted from ${docs.docsUrl} for the @stevejuma/ui native-CSS catalog. -->\n\n`;
  return banner + md;
}

/** Combined Usage SFC with published package import paths. */
function buildPackageUsageSource(
  docs: UpstreamDocs,
  component: string,
): string {
  const script = docs.usage.script
    ? rewritePackageImports(docs.usage.script, component).trim()
    : "";
  const markup = docs.usage.markup
    ? rewritePackageImports(docs.usage.markup, component).trim()
    : "";
  if (script && markup) return `${script}\n\n${markup}`;
  return script || markup;
}

/** Family-root relative imports → examples/ subdirectory relative imports. */
function adjustImportsForExamplesDir(code: string): string {
  return code
    .replaceAll('from "./index.js"', 'from "../index.js"')
    .replace(
      /from\s+["']\.\.\/([a-z][a-z0-9-]*)\/index\.js["']/g,
      (_m, family: string) => `from "../../${family}/index.js"`,
    );
}

function ensureTooltipProvider(code: string): string {
  if (!/\bTooltip\.Root\b/.test(code)) return code;
  if (/\bTooltip\.Provider\b/.test(code)) return code;
  const scriptMatch = /^([\s\S]*?<\/script>\s*)([\s\S]*)$/m.exec(code);
  if (!scriptMatch) return code;
  const [, script, markup] = scriptMatch;
  return `${script}<Tooltip.Provider delayDuration={0}>\n${markup.trim()}\n</Tooltip.Provider>\n`;
}

function emitExampleComponent(code: string): string {
  const adjusted = ensureTooltipProvider(
    adjustImportsForExamplesDir(code),
  ).trim();
  // Prefer a JS banner inside <script> — leading HTML comments are scraped into
  // Storybook autodocs story descriptions.
  if (adjusted.startsWith("<script")) {
    return (
      adjusted.replace(
        /(<script\b[^>]*>)/,
        "$1\n  // @generated by ui-generator — do not edit\n",
      ) + "\n"
    );
  }
  return `${adjusted}\n`;
}

/** Consumer-facing SFC source for Canvas "Show code" (not the Story wrapper). */
function buildExampleDocsSource(component: string, code: string): string {
  return rewritePackageImports(
    ensureTooltipProvider(code.trim()),
    component,
  ).trim();
}

/**
 * Keep example SFCs out of Story `parameters={{...}}` literals — `{#each}` / `{tag}`
 * inside those strings breaks the Svelte / svelte-csf indexer.
 */
function emitExampleSourcesModule(args: {
  component: string;
  examples: RewrittenExample[];
}): string {
  const entries = args.examples
    .map((ex) => {
      const exportName = toPascalCase(ex.example.slug);
      const source = buildExampleDocsSource(args.component, ex.code);
      return `export const ${exportName} = ${JSON.stringify(source)};`;
    })
    .join("\n");
  return `// @generated by ui-generator — do not edit
${entries}
`;
}

function emitExamplesStories(args: {
  component: string;
  storyTitle: string;
  examples: RewrittenExample[];
}): string {
  const { storyTitle, examples } = args;
  const pascal = toPascalCase(args.component);
  const imports = examples
    .map(
      (ex) =>
        `  import ${toPascalCase(ex.example.slug)}Example from "./examples/${ex.example.slug}.svelte";`,
    )
    .join("\n");

  const stories = examples
    .map((ex) => {
      const comp = `${toPascalCase(ex.example.slug)}Example`;
      const exportName = toPascalCase(ex.example.slug);
      const descriptionEntry = ex.example.description
        ? `
      description: {
        story: ${JSON.stringify(ex.example.description)},
      },`
        : "";
      // Visual baselines cover these demos so style extraction regressions surface
      // in Playwright. a11y stays todo — curated hand stories own a11y gates.
      // Explicit exportName keeps MDX <Canvas of={...}> references stable.
      // docs.source comes from *.example-sources.ts (avoids embedding Svelte markup
      // in this file's mustache expressions).
      return `<Story
  name=${JSON.stringify(ex.example.name)}
  exportName=${JSON.stringify(exportName)}
  tags={["upstream-example"]}
  parameters={{
    a11y: { test: "todo" },
    docs: {${descriptionEntry}
      source: {
        code: exampleSources.${exportName},
        language: "html",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <${comp} />
    </div>
  {/snippet}
</Story>`;
    })
    .join("\n\n");

  return `<script module lang="ts">
  // @generated by ui-generator — do not edit
  import { defineMeta } from "@storybook/addon-svelte-csf";
  import * as ${pascal} from "./index.js";
  import * as exampleSources from "./${pascal}.example-sources.js";
${imports}

  const { Story } = defineMeta({
    title: ${JSON.stringify(storyTitle)},
    component: ${storyMetaComponentExpr(args.component, pascal)},
  });
</script>

${stories}
`;
}

function emitMdx(args: {
  component: string;
  docs: UpstreamDocs;
  examples: RewrittenExample[];
}): string {
  const pascal = toPascalCase(args.component);
  const usage = buildPackageUsageSource(args.docs, args.component);
  const hasExamples = args.examples.length > 0;
  const exampleSections = args.examples
    .map((ex) => {
      const exportName = toPascalCase(ex.example.slug);
      const prose = ex.example.description
        ? `\n${ex.example.description}\n`
        : "\n";
      return `### ${ex.example.name}
${prose}
<Canvas of={${pascal}Variations.${exportName}} meta={${pascal}Variations} />
`;
    })
    .join("\n");

  // Source uses Storybook's highlighter. `html` is the closest supported lang
  // for Svelte SFCs (svelte is not in the built-in language list).
  const usageSource = usage
    ? `\n<Source language="html" code={${JSON.stringify(usage)}} />\n`
    : "\n";

  const variationsImport = hasExamples
    ? `import * as ${pascal}Variations from "./${pascal}.variations.stories.svelte";\n`
    : "";

  const examplesSection = hasExamples
    ? `\n## Examples\n\n${exampleSections}\n`
    : "";

  return `import { Meta, Canvas, Controls, Primary, Source } from "@storybook/addon-docs/blocks";
import * as ${pascal}Stories from "./${pascal}.stories.svelte";
${variationsImport}
{/* @generated by ui-generator — do not edit */}

<Meta of={${pascal}Stories} />

# ${args.docs.title}

${args.docs.description}

Adapted from the upstream [shadcn-svelte docs](${args.docs.docsUrl}).

## Usage
${usageSource}
<Primary />

<Controls />
${examplesSection}`;
}

export function emitDocsArtifacts(args: {
  targetDir: string;
  component: string;
  storyTitle: string;
  docs: UpstreamDocs;
  examples: RewrittenExample[];
}): string[] {
  const { targetDir, component, storyTitle, docs, examples } = args;
  const pascal = toPascalCase(component);
  const written: string[] = [];

  mkdirSync(targetDir, { recursive: true });
  const examplesDir = path.join(targetDir, "examples");
  mkdirSync(examplesDir, { recursive: true });

  const docsMdPath = path.join(targetDir, `${component}.docs.md`);
  writeFileSync(docsMdPath, rewriteDocsMarkdown(docs, component));
  written.push(docsMdPath);

  // Older emit used `*.examples.stories.svelte`, which sorts before the hand
  // `*.stories.svelte` file and steals the primary Docs canvas.
  const legacyExamplesStories = path.join(
    targetDir,
    `${pascal}.examples.stories.svelte`,
  );
  if (existsSync(legacyExamplesStories)) {
    unlinkSync(legacyExamplesStories);
    written.push(legacyExamplesStories);
  }

  const keepSlugs = new Set(examples.map((ex) => `${ex.example.slug}.svelte`));
  for (const ex of examples) {
    const filePath = path.join(examplesDir, `${ex.example.slug}.svelte`);
    writeFileSync(filePath, emitExampleComponent(ex.code));
    written.push(filePath);
  }
  // Drop demos that are no longer included (skipped or removed upstream).
  if (existsSync(examplesDir)) {
    for (const name of readdirSync(examplesDir)) {
      if (!name.endsWith(".svelte") || keepSlugs.has(name)) continue;
      const stale = path.join(examplesDir, name);
      unlinkSync(stale);
      written.push(stale);
    }
  }

  // Name sorts after `${pascal}.stories.svelte` so curated stories stay primary.
  const storiesPath = path.join(
    targetDir,
    `${pascal}.variations.stories.svelte`,
  );
  const sourcesPath = path.join(targetDir, `${pascal}.example-sources.ts`);
  if (examples.length > 0) {
    writeFileSync(
      sourcesPath,
      emitExampleSourcesModule({ component, examples }),
    );
    written.push(sourcesPath);
    writeFileSync(
      storiesPath,
      emitExamplesStories({ component, storyTitle, examples }),
    );
    written.push(storiesPath);
  } else {
    if (existsSync(storiesPath)) {
      // Empty defineMeta files break Storybook's svelte-csf indexer.
      unlinkSync(storiesPath);
      written.push(storiesPath);
    }
    if (existsSync(sourcesPath)) {
      unlinkSync(sourcesPath);
      written.push(sourcesPath);
    }
  }

  const mdxPath = path.join(targetDir, `${pascal}.mdx`);
  writeFileSync(
    mdxPath,
    emitMdx({
      component,
      docs,
      examples,
    }),
  );
  written.push(mdxPath);

  return written;
}

export { toPascalCase };
