<script module lang="ts">
  // @generated by ui-generator — do not edit
  import { defineMeta } from "@storybook/addon-svelte-csf";
  import * as Empty from "./index.js";
  import * as exampleSources from "./Empty.example-sources.js";
  import PreviewExample from "./examples/preview.svelte";
  import OutlineExample from "./examples/outline.svelte";
  import BackgroundExample from "./examples/background.svelte";

  const { Story } = defineMeta({
    title: "Shadcn/Feedback/Empty",
    component: Empty.Empty,
  });
</script>

<Story
  name="Preview"
  exportName="Preview"
  tags={["upstream-example", "visual-approved"]}
  parameters={{
    visualDelta: {
      images: ["/visual-baselines/shadcn/empty/preview-chromium.png"],
      opacity: 0.5,
      colorInversion: false,
      align: "canvas",
      placement: "right",
    },
    a11y: { test: "todo" },
    docs: {
      source: {
        code: exampleSources.Preview,
        language: "tsx",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <PreviewExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Outline"
  exportName="Outline"
  tags={["upstream-example", "visual-approved"]}
  parameters={{
    visualDelta: {
      images: ["/visual-baselines/shadcn/empty/outline-chromium.png"],
      opacity: 0.5,
      colorInversion: false,
      align: "canvas",
      placement: "right",
    },
    a11y: { test: "todo" },
    docs: {
      description: {
        story:
          "Use the `border` utility class to create an outline empty state.",
      },
      source: {
        code: exampleSources.Outline,
        language: "tsx",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <OutlineExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Background"
  exportName="Background"
  tags={["upstream-example", "visual-approved"]}
  parameters={{
    visualDelta: {
      images: ["/visual-baselines/shadcn/empty/background-chromium.png"],
      opacity: 0.5,
      colorInversion: false,
      align: "canvas",
      placement: "right",
    },
    a11y: { test: "todo" },
    docs: {
      description: {
        story:
          "Use the `bg-*` and `bg-gradient-*` utilities to add a background to the empty state.",
      },
      source: {
        code: exampleSources.Background,
        language: "tsx",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <BackgroundExample />
    </div>
  {/snippet}
</Story>
