<script module lang="ts">
  // @generated by ui-generator — do not edit
  import { defineMeta } from "@storybook/addon-svelte-csf";
  import * as Empty from "./index.js";
  import PreviewExample from "./examples/preview.svelte";
  import OutlineExample from "./examples/outline.svelte";
  import BackgroundExample from "./examples/background.svelte";

  const { Story } = defineMeta({
    title: "Shadcn/Feedback/Empty",
    // Prefer the Pascal alias (every family exports it); Root is absent on some simpleRoot barrels.
    component: Empty.Empty,
  });
</script>

<Story
  name="Preview"
  exportName="Preview"
  tags={["upstream-example"]}
  parameters={{
    a11y: { test: "todo" as const },
    docs: {
      description: {
        story: "Use the Empty component to display an empty state.\n\n### [Epicenter](https://github.com/EpicenterHQ/epicenter)\n\n[Local-first, open source apps](https://github.com/EpicenterHQ/epicenter)\n\n[Special Sponsor](https://github.com/EpicenterHQ/epicenter)",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <PreviewExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Outline"
  exportName="Outline"
  tags={["upstream-example"]}
  parameters={{
    a11y: { test: "todo" as const },
    docs: {
      description: {
        story: "Use the `border` utility class to create an outline empty state.",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <OutlineExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Background"
  exportName="Background"
  tags={["upstream-example"]}
  parameters={{
    a11y: { test: "todo" as const },
    docs: {
      description: {
        story: "Use the `bg-*` and `bg-gradient-*` utilities to add a background to the empty state.",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <BackgroundExample />
    </div>
  {/snippet}
</Story>
