<script module lang="ts">
  // @generated by ui-generator — do not edit
  import { defineMeta } from "@storybook/addon-svelte-csf";
  import * as ToggleGroup from "./index.js";
  import * as exampleSources from "./ToggleGroup.example-sources.js";
  import SpacingExample from "./examples/spacing.svelte";
  import OutlineExample from "./examples/outline.svelte";
  import SingleExample from "./examples/single.svelte";
  import SmallExample from "./examples/small.svelte";
  import LargeExample from "./examples/large.svelte";
  import DisabledExample from "./examples/disabled.svelte";
  import Spacing2Example from "./examples/spacing-2.svelte";

  const { Story } = defineMeta({
    title: "Shadcn/Actions/Toggle Group",
    component: ToggleGroup.ToggleGroup,
  });
</script>

<Story
  name="Spacing"
  exportName="Spacing"
  tags={["upstream-example", "visual-approved"]}
  parameters={{
    visualDelta: {
      images: ["/visual-baselines/shadcn/toggle-group/spacing-chromium.png"],
      opacity: 0.5,
      colorInversion: false,
      align: "canvas",
      placement: "right",
    },
    a11y: { test: "todo" },
    docs: {
      source: {
        code: exampleSources.Spacing,
        language: "tsx",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <SpacingExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Outline"
  exportName="Outline"
  tags={["upstream-example", "visual-approved"]}
  parameters={{
    visualDelta: {
      images: ["/visual-baselines/shadcn/toggle-group/outline-chromium.png"],
      opacity: 0.5,
      colorInversion: false,
      align: "canvas",
      placement: "right",
    },
    a11y: { test: "todo" },
    docs: {
      source: {
        code: exampleSources.Outline,
        language: "tsx",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <OutlineExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Single"
  exportName="Single"
  tags={["upstream-example", "visual-approved"]}
  parameters={{
    visualDelta: {
      images: ["/visual-baselines/shadcn/toggle-group/single-chromium.png"],
      opacity: 0.5,
      colorInversion: false,
      align: "canvas",
      placement: "right",
    },
    a11y: { test: "todo" },
    docs: {
      source: {
        code: exampleSources.Single,
        language: "tsx",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <SingleExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Small"
  exportName="Small"
  tags={["upstream-example", "visual-approved"]}
  parameters={{
    visualDelta: {
      images: ["/visual-baselines/shadcn/toggle-group/small-chromium.png"],
      opacity: 0.5,
      colorInversion: false,
      align: "canvas",
      placement: "right",
    },
    a11y: { test: "todo" },
    docs: {
      source: {
        code: exampleSources.Small,
        language: "tsx",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <SmallExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Large"
  exportName="Large"
  tags={["upstream-example", "visual-approved"]}
  parameters={{
    visualDelta: {
      images: ["/visual-baselines/shadcn/toggle-group/large-chromium.png"],
      opacity: 0.5,
      colorInversion: false,
      align: "canvas",
      placement: "right",
    },
    a11y: { test: "todo" },
    docs: {
      source: {
        code: exampleSources.Large,
        language: "tsx",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <LargeExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Disabled"
  exportName="Disabled"
  tags={["upstream-example", "visual-approved"]}
  parameters={{
    visualDelta: {
      images: ["/visual-baselines/shadcn/toggle-group/disabled-chromium.png"],
      opacity: 0.5,
      colorInversion: false,
      align: "canvas",
      placement: "right",
    },
    a11y: { test: "todo" },
    docs: {
      source: {
        code: exampleSources.Disabled,
        language: "tsx",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <DisabledExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Spacing 2"
  exportName="Spacing2"
  tags={["upstream-example", "visual-approved"]}
  parameters={{
    visualDelta: {
      images: ["/visual-baselines/shadcn/toggle-group/spacing-2-chromium.png"],
      opacity: 0.5,
      colorInversion: false,
      align: "canvas",
      placement: "right",
    },
    a11y: { test: "todo" },
    docs: {
      description: {
        story: "Use `spacing={2}` to add spacing between toggle group items.",
      },
      source: {
        code: exampleSources.Spacing2,
        language: "tsx",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <Spacing2Example />
    </div>
  {/snippet}
</Story>
