<script module lang="ts">
  // @generated by ui-generator — do not edit
  import { defineMeta } from "@storybook/addon-svelte-csf";
  import * as ToggleGroup from "./index.js";
  import * as exampleSources from "./ToggleGroup.example-sources.js";
  import PreviewExample from "./examples/preview.svelte";
  import OutlineExample from "./examples/outline.svelte";
  import SingleExample from "./examples/single.svelte";
  import SmallExample from "./examples/small.svelte";
  import LargeExample from "./examples/large.svelte";
  import DisabledExample from "./examples/disabled.svelte";
  import SpacingExample from "./examples/spacing.svelte";

  const { Story } = defineMeta({
    title: "Shadcn/Actions/Toggle Group",
    component: ToggleGroup.ToggleGroup,
  });
</script>

<Story
  name="Preview"
  exportName="Preview"
  tags={["upstream-example"]}
  parameters={{
    a11y: { test: "todo" },
    docs: {
      description: {
        story: "A set of two-state buttons that can be toggled on or off.\n\n[Docs](https://bits-ui.com/docs/components/toggle-group)\n\n[API Reference](https://bits-ui.com/docs/components/toggle-group#api-reference)",
      },
      source: {
        code: exampleSources.Preview,
        language: "html",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <PreviewExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Outline"
  exportName="Outline"
  tags={["upstream-example"]}
  parameters={{
    a11y: { test: "todo" },
    docs: {
      source: {
        code: exampleSources.Outline,
        language: "html",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <OutlineExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Single"
  exportName="Single"
  tags={["upstream-example"]}
  parameters={{
    a11y: { test: "todo" },
    docs: {
      source: {
        code: exampleSources.Single,
        language: "html",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <SingleExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Small"
  exportName="Small"
  tags={["upstream-example"]}
  parameters={{
    a11y: { test: "todo" },
    docs: {
      source: {
        code: exampleSources.Small,
        language: "html",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <SmallExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Large"
  exportName="Large"
  tags={["upstream-example"]}
  parameters={{
    a11y: { test: "todo" },
    docs: {
      source: {
        code: exampleSources.Large,
        language: "html",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <LargeExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Disabled"
  exportName="Disabled"
  tags={["upstream-example"]}
  parameters={{
    a11y: { test: "todo" },
    docs: {
      source: {
        code: exampleSources.Disabled,
        language: "html",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <DisabledExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Spacing"
  exportName="Spacing"
  tags={["upstream-example"]}
  parameters={{
    a11y: { test: "todo" },
    docs: {
      description: {
        story: "Use `spacing={2}` to add spacing between toggle group items.",
      },
      source: {
        code: exampleSources.Spacing,
        language: "html",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <SpacingExample />
    </div>
  {/snippet}
</Story>
