// @generated by ui-generator — do not edit
export const Preview =
  '<script lang="ts">\n\timport { Input } from "@lapismd/design-core/shadcn/input";\n</script>\n\n<Input type="email" placeholder="Email" class="max-w-xs" />';
export const Default =
  '<script lang="ts">\n\timport { Input } from "@lapismd/design-core/shadcn/input";\n</script>\n\n<Input type="email" placeholder="Email" class="max-w-xs" />';
export const File =
  '<script lang="ts">\n\timport { Input } from "@lapismd/design-core/shadcn/input";\n\timport { Label } from "@lapismd/design-core/shadcn/label";\n</script>\n\n<div class="grid w-full max-w-sm items-center gap-1.5">\n\t<Label for="picture">Picture</Label>\n\t<Input id="picture" type="file" />\n</div>';
export const Disabled =
  '<script lang="ts">\n\timport { Input } from "@lapismd/design-core/shadcn/input";\n</script>\n\n<Input disabled type="email" placeholder="Email" class="max-w-sm" />';
export const WithLabel =
  '<script lang="ts">\n\timport { Input } from "@lapismd/design-core/shadcn/input";\n\timport { Label } from "@lapismd/design-core/shadcn/label";\n\n\tconst id = $props.id();\n</script>\n\n<div class="flex w-full max-w-sm flex-col gap-1.5">\n\t<Label for="email-{id}">Email</Label>\n\t<Input type="email" id="email-{id}" placeholder="Email" />\n</div>';
export const WithButton =
  '<script lang="ts">\n\timport { Button } from "@lapismd/design-core/shadcn/button";\n\timport { Input } from "@lapismd/design-core/shadcn/input";\n</script>\n\n<div class="flex w-full max-w-sm items-center gap-2">\n\t<Input type="email" placeholder="Email" />\n\t<Button type="submit" variant="outline">Subscribe</Button>\n</div>';
