<script lang="ts">
  // @generated by ui-generator — do not edit

	import IconBrandJavascript from "@lucide/svelte/icons/file-code";
	import IconCopy from "@lucide/svelte/icons/copy";
	import IconCornerDownLeft from "@lucide/svelte/icons/corner-down-left";
	import IconRefresh from "@lucide/svelte/icons/refresh-cw";

	import * as InputGroup from "../index.js";
</script>

<div class="grid w-full max-w-md gap-4">
	<InputGroup.Root>
		<InputGroup.Addon align="block-start" class="border-b">
			<InputGroup.Text class="font-mono font-medium">
				<IconBrandJavascript />
				script.js
			</InputGroup.Text>
			<InputGroup.Button class="ms-auto" size="icon-xs">
				<IconRefresh />
			</InputGroup.Button>
			<InputGroup.Button variant="ghost" size="icon-xs">
				<IconCopy />
			</InputGroup.Button>
		</InputGroup.Addon>
		<InputGroup.Textarea placeholder="console.log('Hello, world!');" class="min-h-[200px]" />
		<InputGroup.Addon align="block-end" class="border-t">
			<InputGroup.Text>Line 1, Column 1</InputGroup.Text>
			<InputGroup.Button size="sm" class="ms-auto" variant="default">
				Run <IconCornerDownLeft />
			</InputGroup.Button>
		</InputGroup.Addon>
	</InputGroup.Root>
</div>
