<script lang="ts">
  // @generated by ui-generator — do not edit

  import { Checkbox } from "../../checkbox/index.js";
  import { Label } from "../index.js";
</script>

<div>
  <div class="flex items-center space-x-2">
    <Checkbox id="terms" />
    <Label for="terms">Accept terms and conditions</Label>
  </div>
</div>
