<script module lang="ts">
  // @generated by ui-generator — do not edit
  import { defineMeta } from "@storybook/addon-svelte-csf";
  import * as Textarea from "./index.js";
  import * as exampleSources from "./Textarea.example-sources.js";
  import PreviewExample from "./examples/preview.svelte";
  import DefaultExample from "./examples/default.svelte";
  import DisabledExample from "./examples/disabled.svelte";
  import WithLabelExample from "./examples/with-label.svelte";
  import WithTextExample from "./examples/with-text.svelte";
  import WithButtonExample from "./examples/with-button.svelte";

  const { Story } = defineMeta({
    title: "Shadcn/Forms/Textarea",
    component: Textarea.Textarea,
  });
</script>

<Story
  name="Preview"
  exportName="Preview"
  tags={["upstream-example"]}
  parameters={{
    a11y: { test: "todo" },
    docs: {
      description: {
        story: "Displays a form textarea or a component that looks like a textarea.",
      },
      source: {
        code: exampleSources.Preview,
        language: "html",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <PreviewExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Default"
  exportName="Default"
  tags={["upstream-example"]}
  parameters={{
    a11y: { test: "todo" },
    docs: {
      source: {
        code: exampleSources.Default,
        language: "html",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <DefaultExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Disabled"
  exportName="Disabled"
  tags={["upstream-example"]}
  parameters={{
    a11y: { test: "todo" },
    docs: {
      source: {
        code: exampleSources.Disabled,
        language: "html",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <DisabledExample />
    </div>
  {/snippet}
</Story>

<Story
  name="With Label"
  exportName="WithLabel"
  tags={["upstream-example"]}
  parameters={{
    a11y: { test: "todo" },
    docs: {
      source: {
        code: exampleSources.WithLabel,
        language: "html",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <WithLabelExample />
    </div>
  {/snippet}
</Story>

<Story
  name="With Text"
  exportName="WithText"
  tags={["upstream-example"]}
  parameters={{
    a11y: { test: "todo" },
    docs: {
      source: {
        code: exampleSources.WithText,
        language: "html",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <WithTextExample />
    </div>
  {/snippet}
</Story>

<Story
  name="With Button"
  exportName="WithButton"
  tags={["upstream-example"]}
  parameters={{
    a11y: { test: "todo" },
    docs: {
      source: {
        code: exampleSources.WithButton,
        language: "html",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <WithButtonExample />
    </div>
  {/snippet}
</Story>
