<script module lang="ts">
  // @generated by ui-generator — do not edit
  import { defineMeta } from "@storybook/addon-svelte-csf";
  import * as Textarea from "./index.js";
  import PreviewExample from "./examples/preview.svelte";
  import DefaultExample from "./examples/default.svelte";
  import DisabledExample from "./examples/disabled.svelte";
  import WithLabelExample from "./examples/with-label.svelte";
  import WithTextExample from "./examples/with-text.svelte";
  import WithButtonExample from "./examples/with-button.svelte";

  const { Story } = defineMeta({
    title: "Shadcn/Forms/Textarea",
    // Prefer the Pascal alias (every family exports it); Root is absent on some simpleRoot barrels.
    component: Textarea.Textarea,
  });
</script>

<Story
  name="Preview"
  exportName="Preview"
  tags={["upstream-example"]}
  parameters={{
    a11y: { test: "todo" as const },
    docs: {
      description: {
        story: "Displays a form textarea or a component that looks like a textarea.\n\n### [Epicenter](https://github.com/EpicenterHQ/epicenter)\n\n[Local-first, open source apps](https://github.com/EpicenterHQ/epicenter)\n\n[Special Sponsor](https://github.com/EpicenterHQ/epicenter)",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <PreviewExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Default"
  exportName="Default"
  tags={["upstream-example"]}
  parameters={{
    a11y: { test: "todo" as const },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <DefaultExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Disabled"
  exportName="Disabled"
  tags={["upstream-example"]}
  parameters={{
    a11y: { test: "todo" as const },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <DisabledExample />
    </div>
  {/snippet}
</Story>

<Story
  name="With Label"
  exportName="WithLabel"
  tags={["upstream-example"]}
  parameters={{
    a11y: { test: "todo" as const },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <WithLabelExample />
    </div>
  {/snippet}
</Story>

<Story
  name="With Text"
  exportName="WithText"
  tags={["upstream-example"]}
  parameters={{
    a11y: { test: "todo" as const },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <WithTextExample />
    </div>
  {/snippet}
</Story>

<Story
  name="With Button"
  exportName="WithButton"
  tags={["upstream-example"]}
  parameters={{
    a11y: { test: "todo" as const },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <WithButtonExample />
    </div>
  {/snippet}
</Story>
