<script module lang="ts">
  // @generated by ui-generator — do not edit
  import { defineMeta } from "@storybook/addon-svelte-csf";
  import * as Textarea from "./index.js";
  import * as exampleSources from "./Textarea.example-sources.js";
  import PreviewExample from "./examples/preview.svelte";
  import DefaultExample from "./examples/default.svelte";
  import DisabledExample from "./examples/disabled.svelte";
  import WithLabelExample from "./examples/with-label.svelte";
  import WithTextExample from "./examples/with-text.svelte";
  import WithButtonExample from "./examples/with-button.svelte";

  const { Story } = defineMeta({
    title: "Shadcn/Forms/Textarea",
    component: Textarea.Textarea,
  });
</script>

<Story
  name="Preview"
  exportName="Preview"
  tags={["upstream-example", "visual-approved"]}
  parameters={{
    visualDelta: {
      images: ["/visual-baselines/shadcn/textarea/preview-chromium.png"],
      opacity: 0.5,
      colorInversion: false,
      align: "canvas",
      placement: "right",
    },
    a11y: { test: "todo" },
    docs: {
      source: {
        code: exampleSources.Preview,
        language: "tsx",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <PreviewExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Default"
  exportName="Default"
  tags={["upstream-example", "visual-approved"]}
  parameters={{
    visualDelta: {
      images: ["/visual-baselines/shadcn/textarea/default-chromium.png"],
      opacity: 0.5,
      colorInversion: false,
      align: "canvas",
      placement: "right",
    },
    a11y: { test: "todo" },
    docs: {
      source: {
        code: exampleSources.Default,
        language: "tsx",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <DefaultExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Disabled"
  exportName="Disabled"
  tags={["upstream-example", "visual-approved"]}
  parameters={{
    visualDelta: {
      images: ["/visual-baselines/shadcn/textarea/disabled-chromium.png"],
      opacity: 0.5,
      colorInversion: false,
      align: "canvas",
      placement: "right",
    },
    a11y: { test: "todo" },
    docs: {
      source: {
        code: exampleSources.Disabled,
        language: "tsx",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <DisabledExample />
    </div>
  {/snippet}
</Story>

<Story
  name="With Label"
  exportName="WithLabel"
  tags={["upstream-example", "visual-approved"]}
  parameters={{
    visualDelta: {
      images: ["/visual-baselines/shadcn/textarea/with-label-chromium.png"],
      opacity: 0.5,
      colorInversion: false,
      align: "canvas",
      placement: "right",
    },
    a11y: { test: "todo" },
    docs: {
      source: {
        code: exampleSources.WithLabel,
        language: "tsx",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <WithLabelExample />
    </div>
  {/snippet}
</Story>

<Story
  name="With Text"
  exportName="WithText"
  tags={["upstream-example", "visual-approved"]}
  parameters={{
    visualDelta: {
      images: ["/visual-baselines/shadcn/textarea/with-text-chromium.png"],
      opacity: 0.5,
      colorInversion: false,
      align: "canvas",
      placement: "right",
    },
    a11y: { test: "todo" },
    docs: {
      source: {
        code: exampleSources.WithText,
        language: "tsx",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <WithTextExample />
    </div>
  {/snippet}
</Story>

<Story
  name="With Button"
  exportName="WithButton"
  tags={["upstream-example", "visual-approved"]}
  parameters={{
    visualDelta: {
      images: ["/visual-baselines/shadcn/textarea/with-button-chromium.png"],
      opacity: 0.5,
      colorInversion: false,
      align: "canvas",
      placement: "right",
    },
    a11y: { test: "todo" },
    docs: {
      source: {
        code: exampleSources.WithButton,
        language: "tsx",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <WithButtonExample />
    </div>
  {/snippet}
</Story>
