<script module lang="ts">
  // @generated by ui-generator — do not edit
  import { defineMeta } from "@storybook/addon-svelte-csf";
  import * as Popover from "./index.js";
  import * as exampleSources from "./Popover.example-sources.js";
  import PreviewExample from "./examples/preview.svelte";

  const { Story } = defineMeta({
    title: "Shadcn/Overlays/Popover",
    component: Popover.Popover,
  });
</script>

<Story
  name="Preview"
  exportName="Preview"
  tags={["upstream-example", "visual-approved"]}
  parameters={{
    visualDelta: {"images":["/visual-baselines/shadcn/popover/preview-chromium-darwin.png"],"opacity":0.5,"colorInversion":false,"align":"canvas","placement":"right","passThresholdPercent":0.1},
    a11y: { test: "todo" },
    docs: {
      description: {
        story: "Displays rich content in a portal, triggered by a button.\n\n[Docs](https://bits-ui.com/docs/components/popover)\n\n[API Reference](https://bits-ui.com/docs/components/popover#api-reference)",
      },
      source: {
        code: exampleSources.Preview,
        language: "html",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <PreviewExample />
    </div>
  {/snippet}
</Story>
