/** Semantic names for later Tasks components; values live in the scoped CSS companion theme. */
export const tasksThemeTokens = [
  "canvas",
  "shell",
  "surface",
  "surface-raised",
  "ink",
  "muted-ink",
  "divider",
  "focus-ring",
  "accent",
  "accent-ink",
  "selection",
  "danger",
  "success",
  "tip-bg",
  "tip-border",
  "task-row-height",
  "sidebar-width",
  "detail-width",
  "radius-shell",
  "radius-control",
  "radius-pill",
  "space-canvas",
  "space-canvas-compact",
  "gap-nav",
  "shadow-detail",
  "shadow-workspace",
  "title-size",
  "nav-item-height",
  "topbar-height",
  "section-label-size",
  "motion-fast",
  "motion-standard",
] as const;

export type TasksThemeToken = (typeof tasksThemeTokens)[number];
