<script lang="ts">
  // @generated by ui-generator — do not edit

	import { Skeleton } from "../index.js";
</script>

<div class="flex items-center space-x-4">
	<Skeleton class="size-12 rounded-full" />
	<div class="space-y-2">
		<Skeleton class="h-4 w-[250px]" />
		<Skeleton class="h-4 w-[200px]" />
	</div>
</div>
