<script module lang="ts">
  // @generated by ui-generator — do not edit
  import { defineMeta } from "@storybook/addon-svelte-csf";
  import * as DropdownMenu from "./index.js";
  import PreviewExample from "./examples/preview.svelte";
  import CheckboxesExample from "./examples/checkboxes.svelte";
  import RadioGroupExample from "./examples/radio-group.svelte";
  import DialogExample from "./examples/dialog.svelte";

  const { Story } = defineMeta({
    title: "Shadcn/Overlays/Dropdown Menu",
    // Prefer the Pascal alias (every family exports it); Root is absent on some simpleRoot barrels.
    component: DropdownMenu.DropdownMenu,
  });
</script>

<Story
  name="Preview"
  exportName="Preview"
  tags={["upstream-example"]}
  parameters={{
    a11y: { test: "todo" as const },
    docs: {
      description: {
        story: "Displays a menu to the user  such as a set of actions or functions  triggered by a button.\n\n[Docs](https://bits-ui.com/docs/components/dropdown-menu)\n\n[API Reference](https://bits-ui.com/docs/components/dropdown-menu#api-reference)\n\n### [Epicenter](https://github.com/EpicenterHQ/epicenter)\n\n[Local-first, open source apps](https://github.com/EpicenterHQ/epicenter)\n\n[Special Sponsor](https://github.com/EpicenterHQ/epicenter)",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <PreviewExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Checkboxes"
  exportName="Checkboxes"
  tags={["upstream-example"]}
  parameters={{
    a11y: { test: "todo" as const },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <CheckboxesExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Radio Group"
  exportName="RadioGroup"
  tags={["upstream-example"]}
  parameters={{
    a11y: { test: "todo" as const },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <RadioGroupExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Dialog"
  exportName="Dialog"
  tags={["upstream-example"]}
  parameters={{
    a11y: { test: "todo" as const },
    docs: {
      description: {
        story: "This example shows how to open a dialog from a dropdown menu.",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <DialogExample />
    </div>
  {/snippet}
</Story>
