<script module lang="ts">
  // @generated by ui-generator — do not edit
  import { defineMeta } from "@storybook/addon-svelte-csf";
  import * as DropdownMenu from "./index.js";
  import * as exampleSources from "./DropdownMenu.example-sources.js";
  import PreviewExample from "./examples/preview.svelte";
  import CheckboxesExample from "./examples/checkboxes.svelte";
  import RadioGroupExample from "./examples/radio-group.svelte";
  import DialogExample from "./examples/dialog.svelte";

  const { Story } = defineMeta({
    title: "Shadcn/Overlays/Dropdown Menu",
    component: DropdownMenu.DropdownMenu,
  });
</script>

<Story
  name="Preview"
  exportName="Preview"
  tags={["upstream-example", "visual-failed", "skip-visual"]}
  parameters={{
    a11y: { test: "todo" },
    docs: {
      source: {
        code: exampleSources.Preview,
        language: "html",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <PreviewExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Checkboxes"
  exportName="Checkboxes"
  tags={["upstream-example", "visual-failed"]}
  parameters={{
    a11y: { test: "todo" },
    docs: {
      source: {
        code: exampleSources.Checkboxes,
        language: "html",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <CheckboxesExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Radio Group"
  exportName="RadioGroup"
  tags={["upstream-example", "visual-failed"]}
  parameters={{
    a11y: { test: "todo" },
    docs: {
      source: {
        code: exampleSources.RadioGroup,
        language: "html",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <RadioGroupExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Dialog"
  exportName="Dialog"
  tags={["upstream-example", "visual-failed"]}
  parameters={{
    a11y: { test: "todo" },
    docs: {
      description: {
        story: "This example shows how to open a dialog from a dropdown menu.",
      },
      source: {
        code: exampleSources.Dialog,
        language: "html",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <DialogExample />
    </div>
  {/snippet}
</Story>
