<script module lang="ts">
  // @generated by ui-generator — do not edit
  import { defineMeta } from "@storybook/addon-svelte-csf";
  import * as Drawer from "./index.js";
  import * as exampleSources from "./Drawer.example-sources.js";
  import PreviewExample from "./examples/preview.svelte";
  import SidesExample from "./examples/sides.svelte";

  const { Story } = defineMeta({
    title: "Shadcn/Overlays/Drawer",
    component: Drawer.Drawer,
  });
</script>

<Story
  name="Preview"
  exportName="Preview"
  tags={["upstream-example"]}
  parameters={{
    a11y: { test: "todo" },
    docs: {
      source: {
        code: exampleSources.Preview,
        language: "html",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <PreviewExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Sides"
  exportName="Sides"
  tags={["upstream-example"]}
  parameters={{
    a11y: { test: "todo" },
    docs: {
      description: {
        story:
          "Use the `direction` prop to set the side of the drawer. Available options are `top`, `right`, `bottom`, and `left`.",
      },
      source: {
        code: exampleSources.Sides,
        language: "html",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <SidesExample />
    </div>
  {/snippet}
</Story>
