<script module lang="ts">
  // @generated by ui-generator — do not edit
  import { defineMeta } from "@storybook/addon-svelte-csf";
  import * as Badge from "./index.js";
  import * as exampleSources from "./Badge.example-sources.js";
  import PreviewExample from "./examples/preview.svelte";
  import LinkExample from "./examples/link.svelte";

  const { Story } = defineMeta({
    title: "Shadcn/Data/Badge",
    component: Badge.Badge,
  });
</script>

<Story
  name="Preview"
  exportName="Preview"
  tags={["upstream-example"]}
  parameters={{
    a11y: { test: "todo" },
    docs: {
      description: {
        story: "Displays a badge or a component that looks like a badge.",
      },
      source: {
        code: exampleSources.Preview,
        language: "html",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <PreviewExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Link"
  exportName="Link"
  tags={["upstream-example"]}
  parameters={{
    a11y: { test: "todo" },
    docs: {
      description: {
        story: "You can use the `badgeVariants` helper to create a link that looks like a badge.",
      },
      source: {
        code: exampleSources.Link,
        language: "html",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <LinkExample />
    </div>
  {/snippet}
</Story>
