<script module lang="ts">
  // @generated by ui-generator — do not edit
  import { defineMeta } from "@storybook/addon-svelte-csf";
  import * as Sidebar from "./index.js";
  import * as exampleSources from "./Sidebar.example-sources.js";
  import YourFirstSidebarExample from "./examples/your-first-sidebar.svelte";
  import SidebarHeaderExample from "./examples/sidebar-header.svelte";
  import SidebarFooterExample from "./examples/sidebar-footer.svelte";
  import SidebarGroupExample from "./examples/sidebar-group.svelte";
  import CollapsibleSidebarGroupExample from "./examples/collapsible-sidebar-group.svelte";
  import SidebarGroupactionExample from "./examples/sidebar-groupaction.svelte";
  import SidebarMenuExample from "./examples/sidebar-menu.svelte";
  import DropdownmenuExample from "./examples/dropdownmenu.svelte";
  import SidebarMenusubExample from "./examples/sidebar-menusub.svelte";
  import CollapsibleSidebarMenuExample from "./examples/collapsible-sidebar-menu.svelte";
  import SidebarMenubadgeExample from "./examples/sidebar-menubadge.svelte";
  import ControlledSidebarExample from "./examples/controlled-sidebar.svelte";

  const { Story } = defineMeta({
    title: "Shadcn/Layout/Sidebar",
    component: Sidebar.Provider,
  });
</script>

<Story
  name="Your First Sidebar"
  exportName="YourFirstSidebar"
  tags={["upstream-example", "visual-pending"]}
  parameters={{
    visualDelta: {
      images: [
        "/visual-baselines/shadcn/sidebar/your-first-sidebar-chromium-darwin.png",
      ],
      opacity: 0.5,
      colorInversion: false,
      align: "canvas",
      placement: "right",
      passThresholdPercent: 0.1,
    },
    a11y: { test: "todo" },
    docs: {
      description: {
        story:
          "Let's start with the most basic sidebar. A collapsible sidebar with a menu.\n\nAdd a `Sidebar.Provider` and `Sidebar.Trigger` at the root of your application.\n\nCreate a new sidebar component at `src/lib/components/app-sidebar.svelte`.\n\nNow, let's add a `Sidebar.Menu` to the sidebar.\n\nWe'll use the `Sidebar.Menu` component in a `Sidebar.Group`.\n\nYou've created your first sidebar.",
      },
      source: {
        code: exampleSources.YourFirstSidebar,
        language: "html",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="h-[480px] p-0">
      <YourFirstSidebarExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Sidebar.Header"
  exportName="SidebarHeader"
  tags={["upstream-example", "visual-failed"]}
  parameters={{
    visualDelta: {
      images: [
        "/visual-baselines/shadcn/sidebar/sidebar-header-chromium-darwin.png",
      ],
      opacity: 0.5,
      colorInversion: false,
      align: "canvas",
      placement: "right",
      passThresholdPercent: 0.1,
    },
    a11y: { test: "todo" },
    docs: {
      description: {
        story:
          "Use the `Sidebar.Header` component to add a sticky header to the sidebar.\n\nThe following example adds a `DropdownMenu` to the `Sidebar.Header`.",
      },
      source: {
        code: exampleSources.SidebarHeader,
        language: "html",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="h-[480px] p-0">
      <SidebarHeaderExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Sidebar.Footer"
  exportName="SidebarFooter"
  tags={["upstream-example", "visual-failed"]}
  parameters={{
    visualDelta: {
      images: [
        "/visual-baselines/shadcn/sidebar/sidebar-footer-chromium-darwin.png",
      ],
      opacity: 0.5,
      colorInversion: false,
      align: "canvas",
      placement: "right",
      passThresholdPercent: 0.1,
    },
    a11y: { test: "todo" },
    docs: {
      description: {
        story:
          "Use the `Sidebar.Footer` component to add a sticky footer to the sidebar.\n\nThe following example adds a `DropdownMenu` to the `Sidebar.Footer`.",
      },
      source: {
        code: exampleSources.SidebarFooter,
        language: "html",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="h-[480px] p-0">
      <SidebarFooterExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Sidebar.Group"
  exportName="SidebarGroup"
  tags={["upstream-example", "visual-failed"]}
  parameters={{
    visualDelta: {
      images: [
        "/visual-baselines/shadcn/sidebar/sidebar-group-chromium-darwin.png",
      ],
      opacity: 0.5,
      colorInversion: false,
      align: "canvas",
      placement: "right",
      passThresholdPercent: 0.1,
    },
    a11y: { test: "todo" },
    docs: {
      description: {
        story:
          "Use the `Sidebar.Group` component to create a section within the sidebar.\n\nA `Sidebar.Group` has a `Sidebar.GroupLabel`, a `Sidebar.GroupContent` and an optional `Sidebar.GroupAction`.",
      },
      source: {
        code: exampleSources.SidebarGroup,
        language: "html",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="h-[480px] p-0">
      <SidebarGroupExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Collapsible Sidebar.Group"
  exportName="CollapsibleSidebarGroup"
  tags={["upstream-example", "visual-failed"]}
  parameters={{
    visualDelta: {
      images: [
        "/visual-baselines/shadcn/sidebar/collapsible-sidebar-group-chromium-darwin.png",
      ],
      opacity: 0.5,
      colorInversion: false,
      align: "canvas",
      placement: "right",
      passThresholdPercent: 0.1,
    },
    a11y: { test: "todo" },
    docs: {
      description: {
        story:
          "To make a `Sidebar.Group` collapsible, wrap it in a `Collapsible`.",
      },
      source: {
        code: exampleSources.CollapsibleSidebarGroup,
        language: "html",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="h-[480px] p-0">
      <CollapsibleSidebarGroupExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Sidebar.GroupAction"
  exportName="SidebarGroupaction"
  tags={["upstream-example", "visual-failed"]}
  parameters={{
    visualDelta: {
      images: [
        "/visual-baselines/shadcn/sidebar/sidebar-groupaction-chromium-darwin.png",
      ],
      opacity: 0.5,
      colorInversion: false,
      align: "canvas",
      placement: "right",
      passThresholdPercent: 0.1,
    },
    a11y: { test: "todo" },
    docs: {
      description: {
        story:
          "Use the `Sidebar.GroupAction` component to add an action to a `Sidebar.Group`.",
      },
      source: {
        code: exampleSources.SidebarGroupaction,
        language: "html",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="h-[480px] p-0">
      <SidebarGroupactionExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Sidebar.Menu"
  exportName="SidebarMenu"
  tags={["upstream-example", "visual-failed"]}
  parameters={{
    visualDelta: {
      images: [
        "/visual-baselines/shadcn/sidebar/sidebar-menu-chromium-darwin.png",
      ],
      opacity: 0.5,
      colorInversion: false,
      align: "canvas",
      placement: "right",
      passThresholdPercent: 0.1,
    },
    a11y: { test: "todo" },
    docs: {
      description: {
        story:
          "The `Sidebar.Menu` component is used for building a menu within a `Sidebar.Group`.\n\nA `Sidebar.Menu` is composed of `Sidebar.MenuItem`, `Sidebar.MenuButton`, `Sidebar.MenuAction`, and `Sidebar.MenuSub` components.\n\nHere's an example of a `Sidebar.Menu` component rendering a list of projects.",
      },
      source: {
        code: exampleSources.SidebarMenu,
        language: "html",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="h-[480px] p-0">
      <SidebarMenuExample />
    </div>
  {/snippet}
</Story>

<Story
  name="DropdownMenu"
  exportName="Dropdownmenu"
  tags={["upstream-example", "visual-pending"]}
  parameters={{
    visualDelta: {
      images: [
        "/visual-baselines/shadcn/sidebar/dropdownmenu-chromium-darwin.png",
      ],
      opacity: 0.5,
      colorInversion: false,
      align: "canvas",
      placement: "right",
      passThresholdPercent: 0.1,
    },
    a11y: { test: "todo" },
    docs: {
      description: {
        story:
          "Here's an example of a `Sidebar.MenuAction` that renders a `DropdownMenu`.",
      },
      source: {
        code: exampleSources.Dropdownmenu,
        language: "html",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="h-[480px] p-0">
      <DropdownmenuExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Sidebar.MenuSub"
  exportName="SidebarMenusub"
  tags={["upstream-example", "visual-failed"]}
  parameters={{
    visualDelta: {
      images: [
        "/visual-baselines/shadcn/sidebar/sidebar-menusub-chromium-darwin.png",
      ],
      opacity: 0.5,
      colorInversion: false,
      align: "canvas",
      placement: "right",
      passThresholdPercent: 0.1,
    },
    a11y: { test: "todo" },
    docs: {
      description: {
        story:
          "The `Sidebar.MenuSub` component is used to render a submenu within a `Sidebar.Menu`.\n\nUse `Sidebar.MenuSubItem` and `Sidebar.MenuSubButton` to render a submenu item.",
      },
      source: {
        code: exampleSources.SidebarMenusub,
        language: "html",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="h-[480px] p-0">
      <SidebarMenusubExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Collapsible Sidebar.Menu"
  exportName="CollapsibleSidebarMenu"
  tags={["upstream-example", "visual-failed"]}
  parameters={{
    visualDelta: {
      images: [
        "/visual-baselines/shadcn/sidebar/collapsible-sidebar-menu-chromium-darwin.png",
      ],
      opacity: 0.5,
      colorInversion: false,
      align: "canvas",
      placement: "right",
      passThresholdPercent: 0.1,
    },
    a11y: { test: "todo" },
    docs: {
      description: {
        story:
          "To make a `Sidebar.Menu` collapsible, wrap it and the `Sidebar.MenuSub` components in a `Collapsible`.",
      },
      source: {
        code: exampleSources.CollapsibleSidebarMenu,
        language: "html",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="h-[480px] p-0">
      <CollapsibleSidebarMenuExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Sidebar.MenuBadge"
  exportName="SidebarMenubadge"
  tags={["upstream-example", "visual-failed"]}
  parameters={{
    visualDelta: {
      images: [
        "/visual-baselines/shadcn/sidebar/sidebar-menubadge-chromium-darwin.png",
      ],
      opacity: 0.5,
      colorInversion: false,
      align: "canvas",
      placement: "right",
      passThresholdPercent: 0.1,
    },
    a11y: { test: "todo" },
    docs: {
      description: {
        story:
          "The `Sidebar.MenuBadge` component is used to render a badge within a `Sidebar.MenuItem`.",
      },
      source: {
        code: exampleSources.SidebarMenubadge,
        language: "html",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="h-[480px] p-0">
      <SidebarMenubadgeExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Controlled Sidebar"
  exportName="ControlledSidebar"
  tags={["upstream-example", "visual-pending"]}
  parameters={{
    visualDelta: {
      images: [
        "/visual-baselines/shadcn/sidebar/controlled-sidebar-chromium-darwin.png",
      ],
      opacity: 0.5,
      colorInversion: false,
      align: "canvas",
      placement: "right",
      passThresholdPercent: 0.1,
    },
    a11y: { test: "todo" },
    docs: {
      description: {
        story:
          "Use Svelte's [Function Binding](https://svelte.dev/docs/svelte/bind#Function-bindings) to control the sidebar state.",
      },
      source: {
        code: exampleSources.ControlledSidebar,
        language: "html",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="h-[480px] p-0">
      <ControlledSidebarExample />
    </div>
  {/snippet}
</Story>
