<script module lang="ts">
  // @generated by ui-generator — do not edit
  import { defineMeta } from "@storybook/addon-svelte-csf";
  import * as Sidebar from "./index.js";
  import * as exampleSources from "./Sidebar.example-sources.js";
  import SidebarProviderExample from "./examples/sidebar-provider.svelte";
  import SidebarRootExample from "./examples/sidebar-root.svelte";
  import SidebarHeaderExample from "./examples/sidebar-header.svelte";
  import SidebarFooterExample from "./examples/sidebar-footer.svelte";
  import SidebarContentExample from "./examples/sidebar-content.svelte";
  import SidebarGroupExample from "./examples/sidebar-group.svelte";
  import CollapsibleSidebarGroupExample from "./examples/collapsible-sidebar-group.svelte";
  import SidebarGroupactionExample from "./examples/sidebar-groupaction.svelte";
  import SidebarMenuExample from "./examples/sidebar-menu.svelte";
  import SidebarMenubuttonExample from "./examples/sidebar-menubutton.svelte";
  import SidebarMenuactionExample from "./examples/sidebar-menuaction.svelte";
  import SidebarMenusubExample from "./examples/sidebar-menusub.svelte";
  import CollapsibleSidebarMenuExample from "./examples/collapsible-sidebar-menu.svelte";
  import SidebarMenubadgeExample from "./examples/sidebar-menubadge.svelte";
  import SidebarMenuskeletonExample from "./examples/sidebar-menuskeleton.svelte";
  import SidebarSeparatorExample from "./examples/sidebar-separator.svelte";
  import SidebarTriggerExample from "./examples/sidebar-trigger.svelte";
  import SidebarRailExample from "./examples/sidebar-rail.svelte";
  import StylingExample from "./examples/styling.svelte";

  const { Story } = defineMeta({
    title: "Shadcn/Layout/Sidebar",
    component: Sidebar.Provider,
  });
</script>

<Story
  name="Sidebar.Provider"
  exportName="SidebarProvider"
  tags={["upstream-example"]}
  parameters={{
    a11y: { test: "todo" },
    docs: {
      description: {
        story: "The `Sidebar.Provider` component is used to provide the sidebar context to the `Sidebar` component. You should always wrap your application in a `Sidebar.Provider` component.\n\n### [Props](#props)\n\n| Name                          | Type                             | Description                                                                                                                                            |\n| ----------------------------------------------------------- | -------------------------------------------------------------- | --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |\n| `open`         | `boolean`                 | Open state of the sidebar (bindable).                                                                                                                  |\n| `onOpenChange` | `(open: boolean) => void` | A callback fired *after* the open state of the sidebar changes if uncontrolled, and *before* the sidebar opens or closes if controlled. |\n\n### [Width](#width)\n\nIf you have a single sidebar in your application, you can use the `SIDEBAR_WIDTH` and `SIDEBAR_WIDTH_MOBILE` constants in `src/lib/components/ui/sidebar/constants.ts` to set the width of the sidebar.\n\nsrc/lib/components/ui/sidebar/constants.ts\n\n```ts\nexport const SIDEBAR_WIDTH = \"16rem\";\nexport const SIDEBAR_WIDTH_MOBILE = \"18rem\";\n```\n\nFor multiple sidebars in your application, you can use the `style` prop to set the width of the sidebar.\n\nTo set the width of the sidebar, you can use the `--sidebar-width` and `--sidebar-width-mobile` CSS variables in the `style` prop.",
      },
      source: {
        code: exampleSources.SidebarProvider,
        language: "html",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <SidebarProviderExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Sidebar.Root"
  exportName="SidebarRoot"
  tags={["upstream-example"]}
  parameters={{
    a11y: { test: "todo" },
    docs: {
      description: {
        story: "The main `Sidebar` component used to render a collapsible sidebar.",
      },
      source: {
        code: exampleSources.SidebarRoot,
        language: "html",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <SidebarRootExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Sidebar.Header"
  exportName="SidebarHeader"
  tags={["upstream-example"]}
  parameters={{
    a11y: { test: "todo" },
    docs: {
      description: {
        story: "Use the `Sidebar.Header` component to add a sticky header to the sidebar.\n\nThe following example adds a `<DropdownMenu>` to the `Sidebar.Header`.\n\nA sidebar header with a dropdown menu.\n\nsrc/lib/components/app-sidebar.svelte",
      },
      source: {
        code: exampleSources.SidebarHeader,
        language: "html",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <SidebarHeaderExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Sidebar.Footer"
  exportName="SidebarFooter"
  tags={["upstream-example"]}
  parameters={{
    a11y: { test: "todo" },
    docs: {
      description: {
        story: "Use the `Sidebar.Footer` component to add a sticky footer to the sidebar.\n\nThe following example adds a `<DropdownMenu>` to the `Sidebar.Footer`.\n\nA sidebar footer with a dropdown menu.\n\nsrc/lib/components/app-sidebar.svelte",
      },
      source: {
        code: exampleSources.SidebarFooter,
        language: "html",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <SidebarFooterExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Sidebar.Content"
  exportName="SidebarContent"
  tags={["upstream-example"]}
  parameters={{
    a11y: { test: "todo" },
    docs: {
      description: {
        story: "The `Sidebar.Content` component is used to wrap the content of the sidebar. This is where you add your `Sidebar.Group` components. It is scrollable.",
      },
      source: {
        code: exampleSources.SidebarContent,
        language: "html",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <SidebarContentExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Sidebar.Group"
  exportName="SidebarGroup"
  tags={["upstream-example"]}
  parameters={{
    a11y: { test: "todo" },
    docs: {
      description: {
        story: "Use the `Sidebar.Group` component to create a section within the sidebar.\n\nA `Sidebar.Group` has a `Sidebar.GroupLabel`, a `Sidebar.GroupContent` and an optional `Sidebar.GroupAction`.\n\nA sidebar group.",
      },
      source: {
        code: exampleSources.SidebarGroup,
        language: "html",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <SidebarGroupExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Collapsible Sidebar.Group"
  exportName="CollapsibleSidebarGroup"
  tags={["upstream-example"]}
  parameters={{
    a11y: { test: "todo" },
    docs: {
      description: {
        story: "To make a `Sidebar.Group` collapsible, wrap it in a `Collapsible`.\n\nA collapsible sidebar group.",
      },
      source: {
        code: exampleSources.CollapsibleSidebarGroup,
        language: "html",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <CollapsibleSidebarGroupExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Sidebar.GroupAction"
  exportName="SidebarGroupaction"
  tags={["upstream-example"]}
  parameters={{
    a11y: { test: "todo" },
    docs: {
      description: {
        story: "Use the `Sidebar.GroupAction` component to add an action to a `Sidebar.Group`.",
      },
      source: {
        code: exampleSources.SidebarGroupaction,
        language: "html",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <SidebarGroupactionExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Sidebar.Menu"
  exportName="SidebarMenu"
  tags={["upstream-example"]}
  parameters={{
    a11y: { test: "todo" },
    docs: {
      description: {
        story: "The `Sidebar.Menu` component is used for building a menu within a `Sidebar.Group`.\n\nA `Sidebar.Menu` is composed of `Sidebar.MenuItem`, `Sidebar.MenuButton`, `Sidebar.MenuAction`, and `Sidebar.MenuSub` components.\n\n![Sidebar menu](/img/sidebar/sidebar-menu.png) ![Sidebar menu](/img/sidebar/sidebar-menu-dark.png)\n\nHere's an example of a `Sidebar.Menu` component rendering a list of projects.\n\nA sidebar menu with a list of projects.",
      },
      source: {
        code: exampleSources.SidebarMenu,
        language: "html",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <SidebarMenuExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Sidebar.MenuButton"
  exportName="SidebarMenubutton"
  tags={["upstream-example"]}
  parameters={{
    a11y: { test: "todo" },
    docs: {
      description: {
        story: "The `Sidebar.MenuButton` component is used to render a menu button within a `Sidebar.Menu`.\n\n### [Link or Anchor](#link-or-anchor)\n\nBy default, the `Sidebar.MenuButton` renders a button, but you can use the `child` snippet to render a different component such as an `<a>` tag.",
      },
      source: {
        code: exampleSources.SidebarMenubutton,
        language: "html",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <SidebarMenubuttonExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Sidebar.MenuAction"
  exportName="SidebarMenuaction"
  tags={["upstream-example"]}
  parameters={{
    a11y: { test: "todo" },
    docs: {
      description: {
        story: "The `Sidebar.MenuAction` component is used to render a menu action within a `Sidebar.Menu`.\n\nThis button works independently of the `Sidebar.MenuButton`, i.e. you can have the `Sidebar.MenuButton` as a clickable link and the `Sidebar.MenuAction` as a button.",
      },
      source: {
        code: exampleSources.SidebarMenuaction,
        language: "html",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <SidebarMenuactionExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Sidebar.MenuSub"
  exportName="SidebarMenusub"
  tags={["upstream-example"]}
  parameters={{
    a11y: { test: "todo" },
    docs: {
      description: {
        story: "The `Sidebar.MenuSub` component is used to render a submenu within a `Sidebar.Menu`.\n\nUse `Sidebar.MenuSubItem` and `Sidebar.MenuSubButton` to render a submenu item.\n\nA sidebar menu sub.",
      },
      source: {
        code: exampleSources.SidebarMenusub,
        language: "html",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <SidebarMenusubExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Collapsible Sidebar.Menu"
  exportName="CollapsibleSidebarMenu"
  tags={["upstream-example"]}
  parameters={{
    a11y: { test: "todo" },
    docs: {
      description: {
        story: "To make a `Sidebar.Menu` collapsible, wrap it and the `Sidebar.MenuSub` components in a `Collapsible`.\n\nA collapsible sidebar menu.",
      },
      source: {
        code: exampleSources.CollapsibleSidebarMenu,
        language: "html",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <CollapsibleSidebarMenuExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Sidebar.MenuBadge"
  exportName="SidebarMenubadge"
  tags={["upstream-example"]}
  parameters={{
    a11y: { test: "todo" },
    docs: {
      description: {
        story: "The `Sidebar.MenuBadge` component is used to render a badge within a `Sidebar.MenuItem`.\n\nA sidebar menu badge.",
      },
      source: {
        code: exampleSources.SidebarMenubadge,
        language: "html",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <SidebarMenubadgeExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Sidebar.MenuSkeleton"
  exportName="SidebarMenuskeleton"
  tags={["upstream-example"]}
  parameters={{
    a11y: { test: "todo" },
    docs: {
      description: {
        story: "The `Sidebar.MenuSkeleton` component is used to render a skeleton within a `Sidebar.MenuItem`. You can use this to show a loading state while waiting for data to load.",
      },
      source: {
        code: exampleSources.SidebarMenuskeleton,
        language: "html",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <SidebarMenuskeletonExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Sidebar.Separator"
  exportName="SidebarSeparator"
  tags={["upstream-example"]}
  parameters={{
    a11y: { test: "todo" },
    docs: {
      description: {
        story: "The `Sidebar.Separator` component is used to render a separator within a `Sidebar`.",
      },
      source: {
        code: exampleSources.SidebarSeparator,
        language: "html",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <SidebarSeparatorExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Sidebar.Trigger"
  exportName="SidebarTrigger"
  tags={["upstream-example"]}
  parameters={{
    a11y: { test: "todo" },
    docs: {
      description: {
        story: "Use the `Sidebar.Trigger` component to render a button that toggles the sidebar.\n\nThe `Sidebar.Trigger` component must be used within a `Sidebar.Provider`.",
      },
      source: {
        code: exampleSources.SidebarTrigger,
        language: "html",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <SidebarTriggerExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Sidebar.Rail"
  exportName="SidebarRail"
  tags={["upstream-example"]}
  parameters={{
    a11y: { test: "todo" },
    docs: {
      description: {
        story: "The `Sidebar.Rail` component is used to render a rail within a `Sidebar.Root`. This rail can be used to toggle the sidebar.",
      },
      source: {
        code: exampleSources.SidebarRail,
        language: "html",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <SidebarRailExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Styling"
  exportName="Styling"
  tags={["upstream-example"]}
  parameters={{
    a11y: { test: "todo" },
    docs: {
      description: {
        story: "Here are some tips for styling the sidebar based on different states.\n\n- **Styling an element based on the sidebar collapsible state.** The following will hide the `Sidebar.Group` when the sidebar is in `icon` mode.",
      },
      source: {
        code: exampleSources.Styling,
        language: "html",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <StylingExample />
    </div>
  {/snippet}
</Story>
