<script module lang="ts">
  // @generated by ui-generator — do not edit
  import { defineMeta } from "@storybook/addon-svelte-csf";
  import * as Command from "./index.js";
  import PreviewExample from "./examples/preview.svelte";
  import DialogExample from "./examples/dialog.svelte";

  const { Story } = defineMeta({
    title: "Shadcn/Forms/Command",
    // Prefer the Pascal alias (every family exports it); Root is absent on some simpleRoot barrels.
    component: Command.Command,
  });
</script>

<Story
  name="Preview"
  exportName="Preview"
  tags={["upstream-example"]}
  parameters={{
    a11y: { test: "todo" as const },
    docs: {
      description: {
        story: "Fast, composable, unstyled command menu for Svelte.\n\n[Docs](https://bits-ui.com/docs/components/command)\n\n[API Reference](https://bits-ui.com/docs/components/command#api-reference)\n\n### [Epicenter](https://github.com/EpicenterHQ/epicenter)\n\n[Local-first, open source apps](https://github.com/EpicenterHQ/epicenter)\n\n[Special Sponsor](https://github.com/EpicenterHQ/epicenter)",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <PreviewExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Dialog"
  exportName="Dialog"
  tags={["upstream-example"]}
  parameters={{
    a11y: { test: "todo" as const },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <DialogExample />
    </div>
  {/snippet}
</Story>
