<script module lang="ts">
  // @generated by ui-generator — do not edit
  import { defineMeta } from "@storybook/addon-svelte-csf";
  import * as Skeleton from "./index.js";
  import PreviewExample from "./examples/preview.svelte";
  import CardExample from "./examples/card.svelte";

  const { Story } = defineMeta({
    title: "Shadcn/Feedback/Skeleton",
    // Prefer the Pascal alias (every family exports it); Root is absent on some simpleRoot barrels.
    component: Skeleton.Skeleton,
  });
</script>

<Story
  name="Preview"
  exportName="Preview"
  tags={["upstream-example"]}
  parameters={{
    a11y: { test: "todo" as const },
    docs: {
      description: {
        story: "Use to show a placeholder while content is loading.\n\n### [Epicenter](https://github.com/EpicenterHQ/epicenter)\n\n[Local-first, open source apps](https://github.com/EpicenterHQ/epicenter)\n\n[Special Sponsor](https://github.com/EpicenterHQ/epicenter)",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <PreviewExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Card"
  exportName="Card"
  tags={["upstream-example"]}
  parameters={{
    a11y: { test: "todo" as const },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <CardExample />
    </div>
  {/snippet}
</Story>
