// @generated by ui-generator — do not edit
export const Preview =
  '<script lang="ts">\n\timport { Skeleton } from "@lapismd/design-core/shadcn/skeleton";\n</script>\n\n<div class="flex items-center space-x-4">\n\t<Skeleton class="size-12 rounded-full" />\n\t<div class="space-y-2">\n\t\t<Skeleton class="h-4 w-[250px]" />\n\t\t<Skeleton class="h-4 w-[200px]" />\n\t</div>\n</div>';
export const Card =
  '<script lang="ts">\n\timport { Skeleton } from "@lapismd/design-core/shadcn/skeleton";\n</script>\n\n<div class="flex flex-col space-y-3">\n\t<Skeleton class="h-[125px] w-[250px] rounded-xl" />\n\t<div class="space-y-2">\n\t\t<Skeleton class="h-4 w-[250px]" />\n\t\t<Skeleton class="h-4 w-[200px]" />\n\t</div>\n</div>';
