<script module lang="ts">
  // @generated by ui-generator — do not edit
  import { defineMeta } from "@storybook/addon-svelte-csf";
  import * as Skeleton from "./index.js";
  import * as exampleSources from "./Skeleton.example-sources.js";
  import PreviewExample from "./examples/preview.svelte";
  import CardExample from "./examples/card.svelte";

  const { Story } = defineMeta({
    title: "Shadcn/Feedback/Skeleton",
    component: Skeleton.Skeleton,
  });
</script>

<Story
  name="Preview"
  exportName="Preview"
  tags={["upstream-example", "visual-ready"]}
  parameters={{
    a11y: { test: "todo" },
    docs: {
      source: {
        code: exampleSources.Preview,
        language: "html",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <PreviewExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Card"
  exportName="Card"
  tags={["upstream-example", "visual-ready"]}
  parameters={{
    a11y: { test: "todo" },
    docs: {
      source: {
        code: exampleSources.Card,
        language: "html",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <CardExample />
    </div>
  {/snippet}
</Story>
