<script module lang="ts">
  // @generated by ui-generator — do not edit
  import { defineMeta } from "@storybook/addon-svelte-csf";
  import * as Dialog from "./index.js";
  import PreviewExample from "./examples/preview.svelte";
  import CustomCloseButtonExample from "./examples/custom-close-button.svelte";

  const { Story } = defineMeta({
    title: "Shadcn/Overlays/Dialog",
    // Prefer the Pascal alias (every family exports it); Root is absent on some simpleRoot barrels.
    component: Dialog.Dialog,
  });
</script>

<Story
  name="Preview"
  exportName="Preview"
  tags={["upstream-example"]}
  parameters={{
    a11y: { test: "todo" as const },
    docs: {
      description: {
        story: "A window overlaid on either the primary window or another dialog window, rendering the content underneath inert.\n\n[Docs](https://bits-ui.com/docs/components/dialog)\n\n[API Reference](https://bits-ui.com/docs/components/dialog#api-reference)\n\n### [Epicenter](https://github.com/EpicenterHQ/epicenter)\n\n[Local-first, open source apps](https://github.com/EpicenterHQ/epicenter)\n\n[Special Sponsor](https://github.com/EpicenterHQ/epicenter)",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <PreviewExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Custom close button"
  exportName="CustomCloseButton"
  tags={["upstream-example"]}
  parameters={{
    a11y: { test: "todo" as const },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <CustomCloseButtonExample />
    </div>
  {/snippet}
</Story>
