<script module lang="ts">
  // @generated by ui-generator — do not edit
  import { defineMeta } from "@storybook/addon-svelte-csf";
  import * as Dialog from "./index.js";
  import * as exampleSources from "./Dialog.example-sources.js";
  import PreviewExample from "./examples/preview.svelte";
  import CustomCloseButtonExample from "./examples/custom-close-button.svelte";

  const { Story } = defineMeta({
    title: "Shadcn/Overlays/Dialog",
    component: Dialog.Dialog});
</script>

<Story
  name="Preview"
  exportName="Preview"
  tags={["upstream-example", "skip-visual"]}
  parameters={{
    a11y: { test: "todo" },
    docs: {
      source: {
        code: exampleSources.Preview,
        language: "html",
        type: "code"}}}}
>
  {#snippet template()}
    <div class="p-4">
      <PreviewExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Custom close button"
  exportName="CustomCloseButton"
  tags={["upstream-example", "skip-visual"]}
  parameters={{
    a11y: { test: "todo" },
    docs: {
      source: {
        code: exampleSources.CustomCloseButton,
        language: "html",
        type: "code"}}}}
>
  {#snippet template()}
    <div class="p-4">
      <CustomCloseButtonExample />
    </div>
  {/snippet}
</Story>
