<script module lang="ts">
  // @generated by ui-generator — do not edit
  import { defineMeta } from "@storybook/addon-svelte-csf";
  import * as Accordion from "./index.js";
  import PreviewExample from "./examples/preview.svelte";

  const { Story } = defineMeta({
    title: "Shadcn/Disclosure/Accordion",
    // Prefer the Pascal alias (every family exports it); Root is absent on some simpleRoot barrels.
    component: Accordion.Accordion,
  });
</script>

<Story
  name="Preview"
  exportName="Preview"
  tags={["upstream-example"]}
  parameters={{
    a11y: { test: "todo" as const },
    docs: {
      description: {
        story: "A vertically stacked set of interactive headings that each reveal a section of content.\n\n[Docs](https://bits-ui.com/docs/components/accordion)\n\n[API Reference](https://bits-ui.com/docs/components/accordion#api-reference)\n\n### [Epicenter](https://github.com/EpicenterHQ/epicenter)\n\n[Local-first, open source apps](https://github.com/EpicenterHQ/epicenter)\n\n[Special Sponsor](https://github.com/EpicenterHQ/epicenter)",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <PreviewExample />
    </div>
  {/snippet}
</Story>
