<script module lang="ts">
  // @generated by ui-generator — do not edit
  import { defineMeta } from "@storybook/addon-svelte-csf";
  import * as ScrollArea from "./index.js";
  import * as exampleSources from "./ScrollArea.example-sources.js";
  import PreviewExample from "./examples/preview.svelte";
  import HorizontalScrollingExample from "./examples/horizontal-scrolling.svelte";

  const { Story } = defineMeta({
    title: "Shadcn/Layout/Scroll Area",
    component: ScrollArea.ScrollArea,
  });
</script>

<Story
  name="Preview"
  exportName="Preview"
  tags={["upstream-example", "visual-approved"]}
  parameters={{
    visualDelta: {
      images: ["/visual-baselines/shadcn/scroll-area/preview-chromium.png"],
      opacity: 0.5,
      colorInversion: false,
      align: "canvas",
      placement: "right",
    },
    a11y: { test: "todo" },
    docs: {
      source: {
        code: exampleSources.Preview,
        language: "tsx",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <PreviewExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Horizontal Scrolling"
  exportName="HorizontalScrolling"
  tags={["upstream-example", "visual-approved"]}
  parameters={{
    visualDelta: {
      images: [
        "/visual-baselines/shadcn/scroll-area/horizontal-scrolling-chromium.png",
      ],
      opacity: 0.5,
      colorInversion: false,
      align: "canvas",
      placement: "right",
    },
    a11y: { test: "todo" },
    docs: {
      description: {
        story:
          'Set the `orientation` prop to `"horizontal"` to enable horizontal scrolling.',
      },
      source: {
        code: exampleSources.HorizontalScrolling,
        language: "tsx",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <HorizontalScrollingExample />
    </div>
  {/snippet}
</Story>
