<script module lang="ts">
  // @generated by ui-generator — do not edit
  import { defineMeta } from "@storybook/addon-svelte-csf";
  import * as ScrollArea from "./index.js";
  import PreviewExample from "./examples/preview.svelte";
  import HorizontalScrollingExample from "./examples/horizontal-scrolling.svelte";

  const { Story } = defineMeta({
    title: "Shadcn/Layout/Scroll Area",
    component: ScrollArea.ScrollArea,
  });
</script>

<Story
  name="Preview"
  exportName="Preview"
  tags={["upstream-example"]}
  parameters={{
    a11y: { test: "todo" as const },
    docs: {
      description: {
        story: "Augments native scroll functionality for custom, cross-browser styling.\n\n[Docs](https://bits-ui.com/docs/components/scroll-area)\n\n[API Reference](https://bits-ui.com/docs/components/scroll-area#api-reference)\n\n### [Epicenter](https://github.com/EpicenterHQ/epicenter)\n\n[Local-first, open source apps](https://github.com/EpicenterHQ/epicenter)\n\n[Special Sponsor](https://github.com/EpicenterHQ/epicenter)",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <PreviewExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Horizontal Scrolling"
  exportName="HorizontalScrolling"
  tags={["upstream-example"]}
  parameters={{
    a11y: { test: "todo" as const },
    docs: {
      description: {
        story: "Set the `orientation` prop to `\"horizontal\"` to enable horizontal scrolling.",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <HorizontalScrollingExample />
    </div>
  {/snippet}
</Story>
