// @generated by ui-generator — do not edit
export const Preview =
  '<script lang="ts">\n\timport { Checkbox } from "@lapismd/design-core/shadcn/checkbox";\n\timport { Label } from "@lapismd/design-core/shadcn/label";\n</script>\n\n<div>\n\t<div class="flex items-center space-x-2">\n\t\t<Checkbox id="terms" />\n\t\t<Label for="terms">Accept terms and conditions</Label>\n\t</div>\n</div>';
