<script lang="ts">
  // @generated by ui-generator — do not edit

	import * as Empty from "../index.js";
	import { Button } from "../../button/index.js";
	import CloudIcon from "@lucide/svelte/icons/cloud";
</script>

<Empty.Root class="border border-dashed">
	<Empty.Header>
		<Empty.Media variant="icon">
			<CloudIcon />
		</Empty.Media>
		<Empty.Title>Cloud Storage Empty</Empty.Title>
		<Empty.Description>
			Upload files to your cloud storage to access them anywhere.
		</Empty.Description>
	</Empty.Header>
	<Empty.Content>
		<Button variant="outline" size="sm">Upload Files</Button>
	</Empty.Content>
</Empty.Root>
