<script module lang="ts">
  // @generated by ui-generator — do not edit
  import { defineMeta } from "@storybook/addon-svelte-csf";
  import * as Tooltip from "./index.js";
  import * as exampleSources from "./Tooltip.example-sources.js";
  import PreviewExample from "./examples/preview.svelte";
  import NestedProvidersExample from "./examples/nested-providers.svelte";

  const { Story } = defineMeta({
    title: "Shadcn/Overlays/Tooltip",
    component: Tooltip.Tooltip,
  });
</script>

<Story
  name="Preview"
  exportName="Preview"
  tags={["upstream-example"]}
  parameters={{
    a11y: { test: "todo" },
    docs: {
      description: {
        story: "A popup that displays information related to an element when the element receives keyboard focus or the mouse hovers over it.\n\n[Docs](https://bits-ui.com/docs/components/tooltip)\n\n[API Reference](https://bits-ui.com/docs/components/tooltip#api-reference)",
      },
      source: {
        code: exampleSources.Preview,
        language: "html",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <PreviewExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Nested Providers"
  exportName="NestedProviders"
  tags={["upstream-example"]}
  parameters={{
    a11y: { test: "todo" },
    docs: {
      description: {
        story: "You can nest providers to create groups with different settings. Tooltips use the closest ancestor provider. This is useful when you want instant tooltips in specific areas:",
      },
      source: {
        code: exampleSources.NestedProviders,
        language: "html",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <NestedProvidersExample />
    </div>
  {/snippet}
</Story>
