// @generated by ui-generator — do not edit
export const Preview = "<script lang=\"ts\">\n  import { buttonVariants } from \"@stevejuma/ui/shadcn/button\";\n  import * as Tooltip from \"@stevejuma/ui/shadcn/tooltip\";\n</script>\n<Tooltip.Provider>\n  <Tooltip.Root>\n    <Tooltip.Trigger class={buttonVariants({ variant: \"outline\" })}\n      >Hover</Tooltip.Trigger\n    >\n    <Tooltip.Content>\n      <p>Add to library</p>\n    </Tooltip.Content>\n  </Tooltip.Root>\n</Tooltip.Provider>";
export const NestedProviders = "<Tooltip.Provider delayDuration={0}>\n</Tooltip.Provider>";
