<script module lang="ts">
  // @generated by ui-generator — do not edit
  import { defineMeta } from "@storybook/addon-svelte-csf";
  import * as Resizable from "./index.js";
  import * as exampleSources from "./Resizable.example-sources.js";
  import PreviewExample from "./examples/preview.svelte";
  import VerticalExample from "./examples/vertical.svelte";
  import HandleExample from "./examples/handle.svelte";

  const { Story } = defineMeta({
    title: "Shadcn/Layout/Resizable",
    component: Resizable.PaneGroup,
  });
</script>

<Story
  name="Preview"
  exportName="Preview"
  tags={["upstream-example", "visual-approved"]}
  parameters={{
    a11y: { test: "todo" },
    docs: {
      description: {
        story: "Accessible resizable panel groups and layouts with keyboard support.\n\n[Docs](https://www.paneforge.com)\n\n[API Reference](https://www.paneforge.com/docs/components/pane-group)",
      },
      source: {
        code: exampleSources.Preview,
        language: "html",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <PreviewExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Vertical"
  exportName="Vertical"
  tags={["upstream-example", "visual-approved"]}
  parameters={{
    a11y: { test: "todo" },
    docs: {
      description: {
        story: "Use the `direction` prop to set the direction of the resizable panels.",
      },
      source: {
        code: exampleSources.Vertical,
        language: "html",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <VerticalExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Handle"
  exportName="Handle"
  tags={["upstream-example", "visual-approved"]}
  parameters={{
    a11y: { test: "todo" },
    docs: {
      description: {
        story: "You can set or hide the handle by using the `withHandle` prop on the `ResizableHandle` component.",
      },
      source: {
        code: exampleSources.Handle,
        language: "html",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <HandleExample />
    </div>
  {/snippet}
</Story>
