<script lang="ts">
  // @generated by ui-generator — do not edit

	import { Badge } from "../../badge/index.js";
	import { Spinner } from "../index.js";
</script>

<div class="flex items-center gap-2">
	<Badge>
		<Spinner />
		Syncing
	</Badge>
	<Badge variant="secondary">
		<Spinner />
		Updating
	</Badge>
	<Badge variant="outline">
		<Spinner />
		Loading
	</Badge>
</div>
