<script lang="ts">
  // @generated by ui-generator — do not edit

  import { Button } from "../../button/index.js";
  import { Spinner } from "../index.js";
</script>
<div class="flex flex-col items-center gap-4">
  <Button disabled size="sm">
    <Spinner />
    Loading...
  </Button>
  <Button variant="outline" disabled size="sm">
    <Spinner />
    Please wait
  </Button>
  <Button variant="secondary" disabled size="sm">
    <Spinner />
    Processing
  </Button>
</div>
