<script lang="ts">
  // @generated by ui-generator — do not edit

	import * as Empty from "../../empty/index.js";
	import { Spinner } from "../index.js";
	import { Button } from "../../button/index.js";
</script>

<Empty.Root class="w-full border md:p-6">
	<Empty.Header>
		<Empty.Media variant="icon">
			<Spinner />
		</Empty.Media>
		<Empty.Title>Processing your request</Empty.Title>
		<Empty.Description>
			Please wait while we process your request. Do not refresh the page.
		</Empty.Description>
	</Empty.Header>
	<Empty.Content>
		<Button variant="outline" size="sm">Cancel</Button>
	</Empty.Content>
</Empty.Root>
