<script lang="ts">
  // @generated by ui-generator — do not edit

	import { Spinner } from "../index.js";
</script>

<div class="flex items-center gap-6">
	<Spinner class="size-3" />
	<Spinner class="size-4" />
	<Spinner class="size-6" />
	<Spinner class="size-8" />
</div>
