<script module lang="ts">
  // @generated by ui-generator — do not edit
  import { defineMeta } from "@storybook/addon-svelte-csf";
  import * as InputGroup from "./index.js";
  import PreviewExample from "./examples/preview.svelte";
  import IconExample from "./examples/icon.svelte";
  import TextExample from "./examples/text.svelte";
  import TooltipExample from "./examples/tooltip.svelte";
  import TextareaExample from "./examples/textarea.svelte";
  import SpinnerExample from "./examples/spinner.svelte";
  import LabelExample from "./examples/label.svelte";
  import DropdownExample from "./examples/dropdown.svelte";
  import CustomInputExample from "./examples/custom-input.svelte";

  const { Story } = defineMeta({
    title: "Shadcn/Forms/Input Group",
    component: InputGroup.InputGroup,
  });
</script>

<Story
  name="Preview"
  exportName="Preview"
  tags={["upstream-example"]}
  parameters={{
    a11y: { test: "todo" as const },
    docs: {
      description: {
        story: "Display additional information or actions to an input or textarea.\n\n### [Epicenter](https://github.com/EpicenterHQ/epicenter)\n\n[Local-first, open source apps](https://github.com/EpicenterHQ/epicenter)\n\n[Special Sponsor](https://github.com/EpicenterHQ/epicenter)",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <PreviewExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Icon"
  exportName="Icon"
  tags={["upstream-example"]}
  parameters={{
    a11y: { test: "todo" as const },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <IconExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Text"
  exportName="Text"
  tags={["upstream-example"]}
  parameters={{
    a11y: { test: "todo" as const },
    docs: {
      description: {
        story: "Display additional text information alongside inputs.",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <TextExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Tooltip"
  exportName="Tooltip"
  tags={["upstream-example"]}
  parameters={{
    a11y: { test: "todo" as const },
    docs: {
      description: {
        story: "Add tooltips to provide additional context or help.",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <TooltipExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Textarea"
  exportName="Textarea"
  tags={["upstream-example"]}
  parameters={{
    a11y: { test: "todo" as const },
    docs: {
      description: {
        story: "Input groups also work with textarea components. Use `block-start` or `block-end` for alignment.",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <TextareaExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Spinner"
  exportName="Spinner"
  tags={["upstream-example"]}
  parameters={{
    a11y: { test: "todo" as const },
    docs: {
      description: {
        story: "Show loading indicators while processing input.",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <SpinnerExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Label"
  exportName="Label"
  tags={["upstream-example"]}
  parameters={{
    a11y: { test: "todo" as const },
    docs: {
      description: {
        story: "Add labels within input groups to improve accessibility.",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <LabelExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Dropdown"
  exportName="Dropdown"
  tags={["upstream-example"]}
  parameters={{
    a11y: { test: "todo" as const },
    docs: {
      description: {
        story: "Pair input groups with dropdown menus for complex interactions.",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <DropdownExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Custom Input"
  exportName="CustomInput"
  tags={["upstream-example"]}
  parameters={{
    a11y: { test: "todo" as const },
    docs: {
      description: {
        story: "Add the `data-slot=\"input-group-control\"` attribute to your custom input for automatic behavior and focus state handling.\n\nNo style is applied to the custom input. Apply your own styles using the `class` prop.",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <CustomInputExample />
    </div>
  {/snippet}
</Story>
