<script module lang="ts">
  // @generated by ui-generator — do not edit
  import { defineMeta } from "@storybook/addon-svelte-csf";
  import * as InputGroup from "./index.js";
  import * as exampleSources from "./InputGroup.example-sources.js";
  import PreviewExample from "./examples/preview.svelte";
  import IconExample from "./examples/icon.svelte";
  import TextExample from "./examples/text.svelte";
  import TooltipExample from "./examples/tooltip.svelte";
  import TextareaExample from "./examples/textarea.svelte";
  import SpinnerExample from "./examples/spinner.svelte";
  import LabelExample from "./examples/label.svelte";
  import DropdownExample from "./examples/dropdown.svelte";
  import CustomInputExample from "./examples/custom-input.svelte";

  const { Story } = defineMeta({
    title: "Shadcn/Forms/Input Group",
    component: InputGroup.InputGroup,
  });
</script>

<Story
  name="Preview"
  exportName="Preview"
  tags={["upstream-example"]}
  parameters={{
    a11y: { test: "todo" },
    docs: {
      source: {
        code: exampleSources.Preview,
        language: "html",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <PreviewExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Icon"
  exportName="Icon"
  tags={["upstream-example"]}
  parameters={{
    a11y: { test: "todo" },
    docs: {
      source: {
        code: exampleSources.Icon,
        language: "html",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <IconExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Text"
  exportName="Text"
  tags={["upstream-example"]}
  parameters={{
    a11y: { test: "todo" },
    docs: {
      description: {
        story: "Display additional text information alongside inputs.",
      },
      source: {
        code: exampleSources.Text,
        language: "html",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <TextExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Tooltip"
  exportName="Tooltip"
  tags={["upstream-example"]}
  parameters={{
    a11y: { test: "todo" },
    docs: {
      description: {
        story: "Add tooltips to provide additional context or help.",
      },
      source: {
        code: exampleSources.Tooltip,
        language: "html",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <TooltipExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Textarea"
  exportName="Textarea"
  tags={["upstream-example"]}
  parameters={{
    a11y: { test: "todo" },
    docs: {
      description: {
        story: "Input groups also work with textarea components. Use `block-start` or `block-end` for alignment.",
      },
      source: {
        code: exampleSources.Textarea,
        language: "html",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <TextareaExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Spinner"
  exportName="Spinner"
  tags={["upstream-example"]}
  parameters={{
    a11y: { test: "todo" },
    docs: {
      description: {
        story: "Show loading indicators while processing input.",
      },
      source: {
        code: exampleSources.Spinner,
        language: "html",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <SpinnerExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Label"
  exportName="Label"
  tags={["upstream-example"]}
  parameters={{
    a11y: { test: "todo" },
    docs: {
      description: {
        story: "Add labels within input groups to improve accessibility.",
      },
      source: {
        code: exampleSources.Label,
        language: "html",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <LabelExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Dropdown"
  exportName="Dropdown"
  tags={["upstream-example"]}
  parameters={{
    a11y: { test: "todo" },
    docs: {
      description: {
        story: "Pair input groups with dropdown menus for complex interactions.",
      },
      source: {
        code: exampleSources.Dropdown,
        language: "html",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <DropdownExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Custom Input"
  exportName="CustomInput"
  tags={["upstream-example"]}
  parameters={{
    a11y: { test: "todo" },
    docs: {
      description: {
        story: "Add the `data-slot=\"input-group-control\"` attribute to your custom input for automatic behavior and focus state handling.\n\nNo style is applied to the custom input. Apply your own styles using the `class` prop.",
      },
      source: {
        code: exampleSources.CustomInput,
        language: "html",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <CustomInputExample />
    </div>
  {/snippet}
</Story>
