<script module lang="ts">
  // @generated by ui-generator — do not edit
  import { defineMeta } from "@storybook/addon-svelte-csf";
  import * as Button from "./index.js";
  import PreviewExample from "./examples/preview.svelte";
  import SizeExample from "./examples/size.svelte";
  import DefaultExample from "./examples/default.svelte";
  import OutlineExample from "./examples/outline.svelte";
  import SecondaryExample from "./examples/secondary.svelte";
  import GhostExample from "./examples/ghost.svelte";
  import DestructiveExample from "./examples/destructive.svelte";
  import LinkExample from "./examples/link.svelte";
  import IconExample from "./examples/icon.svelte";
  import WithIconExample from "./examples/with-icon.svelte";
  import RoundedExample from "./examples/rounded.svelte";
  import SpinnerExample from "./examples/spinner.svelte";
  import Link1Example from "./examples/link-1.svelte";

  const { Story } = defineMeta({
    title: "Shadcn/Actions/Button",
    // Prefer the Pascal alias (every family exports it); Root is absent on some simpleRoot barrels.
    component: Button.Button,
  });
</script>

<Story
  name="Preview"
  exportName="Preview"
  tags={["upstream-example"]}
  parameters={{
    a11y: { test: "todo" as const },
    docs: {
      description: {
        story: "Displays a button or a component that looks like a button.\n\n[API Reference](https://bits-ui.com/docs/components/button#api-reference)\n\n### [Epicenter](https://github.com/EpicenterHQ/epicenter)\n\n[Local-first, open source apps](https://github.com/EpicenterHQ/epicenter)\n\n[Special Sponsor](https://github.com/EpicenterHQ/epicenter)\n\n**Updated:** We have updated the button component to add new sizes: `icon-sm` and `icon-lg`. See the [changelog](https://shadcn-svelte.com/docs/components/button#changelog) for more details. Follow the instructions to update your project.",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <PreviewExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Size"
  exportName="Size"
  tags={["upstream-example"]}
  parameters={{
    a11y: { test: "todo" as const },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <SizeExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Default"
  exportName="Default"
  tags={["upstream-example"]}
  parameters={{
    a11y: { test: "todo" as const },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <DefaultExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Outline"
  exportName="Outline"
  tags={["upstream-example"]}
  parameters={{
    a11y: { test: "todo" as const },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <OutlineExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Secondary"
  exportName="Secondary"
  tags={["upstream-example"]}
  parameters={{
    a11y: { test: "todo" as const },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <SecondaryExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Ghost"
  exportName="Ghost"
  tags={["upstream-example"]}
  parameters={{
    a11y: { test: "todo" as const },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <GhostExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Destructive"
  exportName="Destructive"
  tags={["upstream-example"]}
  parameters={{
    a11y: { test: "todo" as const },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <DestructiveExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Link"
  exportName="Link"
  tags={["upstream-example"]}
  parameters={{
    a11y: { test: "todo" as const },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <LinkExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Icon"
  exportName="Icon"
  tags={["upstream-example"]}
  parameters={{
    a11y: { test: "todo" as const },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <IconExample />
    </div>
  {/snippet}
</Story>

<Story
  name="With Icon"
  exportName="WithIcon"
  tags={["upstream-example"]}
  parameters={{
    a11y: { test: "todo" as const },
    docs: {
      description: {
        story: "The spacing between the icon and the text is automatically adjusted based on the size of the button. You do not need any margin on the icon.",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <WithIconExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Rounded"
  exportName="Rounded"
  tags={["upstream-example"]}
  parameters={{
    a11y: { test: "todo" as const },
    docs: {
      description: {
        story: "Use the `rounded-full` class to make the button rounded.",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <RoundedExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Spinner"
  exportName="Spinner"
  tags={["upstream-example"]}
  parameters={{
    a11y: { test: "todo" as const },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <SpinnerExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Link"
  exportName="Link1"
  tags={["upstream-example"]}
  parameters={{
    a11y: { test: "todo" as const },
    docs: {
      description: {
        story: "You can convert the `<button>` into an `<a>` element by simply passing an `href` as a prop.",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <Link1Example />
    </div>
  {/snippet}
</Story>
