<script lang="ts">
  // @generated by ui-generator — do not edit

	import { Label } from "../../label/index.js";
	import { Switch } from "../index.js";
</script>

<div class="flex items-center space-x-2">
	<Switch id="airplane-mode" />
	<Label for="airplane-mode">Airplane Mode</Label>
</div>
