<script lang="ts">
  // @generated by ui-generator — do not edit

  import { Input } from "../index.js";
  import { Label } from "../../label/index.js";
</script>

<div class="grid w-full max-w-sm items-center gap-1.5">
  <Label for="picture">Picture</Label>
  <Input id="picture" type="file" />
</div>
