<script lang="ts">
  // @generated by ui-generator — do not edit

	import { Button } from "../../button/index.js";
	import { Input } from "../index.js";
</script>

<div class="flex w-full max-w-sm items-center gap-2">
	<Input type="email" placeholder="Email" />
	<Button type="submit" variant="outline">Subscribe</Button>
</div>
