<script lang="ts">
  // @generated by ui-generator — do not edit

  import { badgeVariants } from "../index.js";
</script>
<a href="/dashboard" class={badgeVariants({ variant: "outline" })}>Badge</a>
