<script lang="ts">
  // @generated by ui-generator — do not edit

  import { onMount } from "svelte";
  import { Progress } from "../index.js";

  let value = $state(13);

  onMount(() => {
    const timer = setTimeout(() => (value = 66), 500);
    return () => clearTimeout(timer);
  });
</script>

<Progress {value} max={100} class="w-[60%]" />
