<script module lang="ts">
  // @generated by ui-generator — do not edit
  import { defineMeta } from "@storybook/addon-svelte-csf";
  import * as Select from "./index.js";
  import * as exampleSources from "./Select.example-sources.js";
  import ScrollableExample from "./examples/scrollable.svelte";

  const { Story } = defineMeta({
    title: "Shadcn/Forms/Select",
    component: Select.Select});
</script>

<Story
  name="Scrollable"
  exportName="Scrollable"
  tags={["upstream-example", "visual-approved"]}
  parameters={{
    visualDelta: {"images":["/visual-baselines/shadcn/select/scrollable-chromium.png"],"opacity":0.5,"colorInversion":false,"align":"canvas","placement":"right"},
    a11y: { test: "todo" },
    docs: {
      source: {
        code: exampleSources.Scrollable,
        language: "html",
        type: "code"}}}}
>
  {#snippet template()}
    <div class="p-4">
      <ScrollableExample />
    </div>
  {/snippet}
</Story>
