<script module lang="ts">
  // @generated by ui-generator — do not edit
  import { defineMeta } from "@storybook/addon-svelte-csf";
  import * as Select from "./index.js";
  import PreviewExample from "./examples/preview.svelte";
  import ScrollableExample from "./examples/scrollable.svelte";

  const { Story } = defineMeta({
    title: "Shadcn/Forms/Select",
    // Prefer the Pascal alias (every family exports it); Root is absent on some simpleRoot barrels.
    component: Select.Select,
  });
</script>

<Story
  name="Preview"
  exportName="Preview"
  tags={["upstream-example"]}
  parameters={{
    a11y: { test: "todo" as const },
    docs: {
      description: {
        story: "Displays a list of options for the user to pick fromtriggered by a button.\n\n[Docs](https://bits-ui.com/docs/components/select)\n\n[API Reference](https://bits-ui.com/docs/components/select#api-reference)\n\n### [Epicenter](https://github.com/EpicenterHQ/epicenter)\n\n[Local-first, open source apps](https://github.com/EpicenterHQ/epicenter)\n\n[Special Sponsor](https://github.com/EpicenterHQ/epicenter)",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <PreviewExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Scrollable"
  exportName="Scrollable"
  tags={["upstream-example"]}
  parameters={{
    a11y: { test: "todo" as const },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <ScrollableExample />
    </div>
  {/snippet}
</Story>
