<script module lang="ts">
  // @generated by ui-generator — do not edit
  import { defineMeta } from "@storybook/addon-svelte-csf";
  import * as Toggle from "./index.js";
  import PreviewExample from "./examples/preview.svelte";
  import DefaultExample from "./examples/default.svelte";
  import OutlineExample from "./examples/outline.svelte";
  import WithTextExample from "./examples/with-text.svelte";
  import SmallExample from "./examples/small.svelte";
  import LargeExample from "./examples/large.svelte";
  import DisabledExample from "./examples/disabled.svelte";

  const { Story } = defineMeta({
    title: "Shadcn/Actions/Toggle",
    // Prefer the Pascal alias (every family exports it); Root is absent on some simpleRoot barrels.
    component: Toggle.Toggle,
  });
</script>

<Story
  name="Preview"
  exportName="Preview"
  tags={["upstream-example"]}
  parameters={{
    a11y: { test: "todo" as const },
    docs: {
      description: {
        story: "A two-state button that can be either on or off.\n\n[Docs](https://bits-ui.com/docs/components/toggle)\n\n[API Reference](https://bits-ui.com/docs/components/toggle#api-reference)\n\n### [Epicenter](https://github.com/EpicenterHQ/epicenter)\n\n[Local-first, open source apps](https://github.com/EpicenterHQ/epicenter)\n\n[Special Sponsor](https://github.com/EpicenterHQ/epicenter)",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <PreviewExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Default"
  exportName="Default"
  tags={["upstream-example"]}
  parameters={{
    a11y: { test: "todo" as const },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <DefaultExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Outline"
  exportName="Outline"
  tags={["upstream-example"]}
  parameters={{
    a11y: { test: "todo" as const },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <OutlineExample />
    </div>
  {/snippet}
</Story>

<Story
  name="With Text"
  exportName="WithText"
  tags={["upstream-example"]}
  parameters={{
    a11y: { test: "todo" as const },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <WithTextExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Small"
  exportName="Small"
  tags={["upstream-example"]}
  parameters={{
    a11y: { test: "todo" as const },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <SmallExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Large"
  exportName="Large"
  tags={["upstream-example"]}
  parameters={{
    a11y: { test: "todo" as const },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <LargeExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Disabled"
  exportName="Disabled"
  tags={["upstream-example"]}
  parameters={{
    a11y: { test: "todo" as const },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <DisabledExample />
    </div>
  {/snippet}
</Story>
