<script module lang="ts">
  // @generated by ui-generator — do not edit
  import { defineMeta } from "@storybook/addon-svelte-csf";
  import * as ButtonGroup from "./index.js";
  import * as exampleSources from "./ButtonGroup.example-sources.js";
  import PreviewExample from "./examples/preview.svelte";
  import OrientationExample from "./examples/orientation.svelte";
  import SizeExample from "./examples/size.svelte";
  import NestedExample from "./examples/nested.svelte";
  import SeparatorExample from "./examples/separator.svelte";
  import SplitExample from "./examples/split.svelte";
  import InputExample from "./examples/input.svelte";
  import InputGroupExample from "./examples/input-group.svelte";
  import DropdownMenuExample from "./examples/dropdown-menu.svelte";
  import SelectExample from "./examples/select.svelte";
  import PopoverExample from "./examples/popover.svelte";

  const { Story } = defineMeta({
    title: "Shadcn/Actions/Button Group",
    component: ButtonGroup.ButtonGroup,
  });
</script>

<Story
  name="Preview"
  exportName="Preview"
  tags={["upstream-example", "visual-failed"]}
  parameters={{
    a11y: { test: "todo" },
    docs: {
      source: {
        code: exampleSources.Preview,
        language: "html",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <PreviewExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Orientation"
  exportName="Orientation"
  tags={["upstream-example", "visual-failed"]}
  parameters={{
    a11y: { test: "todo" },
    docs: {
      description: {
        story: "Set the `orientation` prop to change the button group layout.",
      },
      source: {
        code: exampleSources.Orientation,
        language: "html",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <OrientationExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Size"
  exportName="Size"
  tags={["upstream-example", "visual-failed"]}
  parameters={{
    a11y: { test: "todo" },
    docs: {
      description: {
        story:
          "Control the size of buttons using the `size` prop on individual buttons.",
      },
      source: {
        code: exampleSources.Size,
        language: "html",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <SizeExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Nested"
  exportName="Nested"
  tags={["upstream-example", "visual-failed"]}
  parameters={{
    a11y: { test: "todo" },
    docs: {
      description: {
        story:
          "Nest `ButtonGroup` components to create button groups with spacing.",
      },
      source: {
        code: exampleSources.Nested,
        language: "html",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <NestedExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Separator"
  exportName="Separator"
  tags={["upstream-example", "visual-failed"]}
  parameters={{
    a11y: { test: "todo" },
    docs: {
      description: {
        story:
          "The `ButtonGroupSeparator` component visually divides buttons within a group.\n\nButtons with variant `outline` do not need a separator since they have a border. For other variants, a separator is recommended to improve the visual hierarchy.",
      },
      source: {
        code: exampleSources.Separator,
        language: "html",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <SeparatorExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Split"
  exportName="Split"
  tags={["upstream-example", "visual-failed"]}
  parameters={{
    a11y: { test: "todo" },
    docs: {
      description: {
        story:
          "Create a split button group by adding two buttons separated by a `ButtonGroupSeparator`.",
      },
      source: {
        code: exampleSources.Split,
        language: "html",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <SplitExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Input"
  exportName="Input"
  tags={["upstream-example", "visual-failed"]}
  parameters={{
    a11y: { test: "todo" },
    docs: {
      description: {
        story: "Wrap an `Input` component with buttons.",
      },
      source: {
        code: exampleSources.Input,
        language: "html",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <InputExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Input Group"
  exportName="InputGroup"
  tags={["upstream-example", "visual-failed"]}
  parameters={{
    a11y: { test: "todo" },
    docs: {
      description: {
        story:
          "Wrap an `InputGroup` component to create complex input layouts.",
      },
      source: {
        code: exampleSources.InputGroup,
        language: "html",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <InputGroupExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Dropdown Menu"
  exportName="DropdownMenu"
  tags={["upstream-example", "visual-failed"]}
  parameters={{
    a11y: { test: "todo" },
    docs: {
      description: {
        story: "Create a split button group with a `DropdownMenu` component.",
      },
      source: {
        code: exampleSources.DropdownMenu,
        language: "html",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <DropdownMenuExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Select"
  exportName="Select"
  tags={["upstream-example", "visual-failed"]}
  parameters={{
    a11y: { test: "todo" },
    docs: {
      description: {
        story: "Pair with a `Select` component.",
      },
      source: {
        code: exampleSources.Select,
        language: "html",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <SelectExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Popover"
  exportName="Popover"
  tags={["upstream-example", "visual-failed"]}
  parameters={{
    a11y: { test: "todo" },
    docs: {
      description: {
        story: "Use with a `Popover` component.",
      },
      source: {
        code: exampleSources.Popover,
        language: "html",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <PopoverExample />
    </div>
  {/snippet}
</Story>
