// @generated by ui-generator — do not edit
export const Preview = "<script lang=\"ts\">\n  import { Label } from \"@stevejuma/ui/shadcn/label\";\n  import { Switch } from \"@stevejuma/ui/shadcn/switch\";\n</script>\n<div class=\"flex items-center space-x-2\">\n  <Switch id=\"airplane-mode\" />\n  <Label for=\"airplane-mode\">Airplane Mode</Label>\n</div>";
