// @generated by ui-generator — do not edit
export const Preview =
  '<script lang="ts">\n\timport { Label } from "@stevejuma/ui/shadcn/label";\n\timport { Switch } from "@stevejuma/ui/shadcn/switch";\n</script>\n\n<div class="flex items-center space-x-2">\n\t<Switch id="airplane-mode" />\n\t<Label for="airplane-mode">Airplane Mode</Label>\n</div>';
