<script module lang="ts">
  // @generated by ui-generator — do not edit
  import { defineMeta } from "@storybook/addon-svelte-csf";
  import * as Breadcrumb from "./index.js";
  import * as exampleSources from "./Breadcrumb.example-sources.js";
  import PreviewExample from "./examples/preview.svelte";
  import CustomSeparatorExample from "./examples/custom-separator.svelte";
  import DropdownExample from "./examples/dropdown.svelte";
  import CollapsedExample from "./examples/collapsed.svelte";
  import LinkComponentExample from "./examples/link-component.svelte";

  const { Story } = defineMeta({
    title: "Shadcn/Navigation/Breadcrumb",
    component: Breadcrumb.Breadcrumb,
  });
</script>

<Story
  name="Preview"
  exportName="Preview"
  tags={["upstream-example", "visual-approved"]}
  parameters={{
    visualDelta: {
      images: [
        "/visual-baselines/shadcn/breadcrumb/preview-chromium-darwin.png",
      ],
      opacity: 0.5,
      colorInversion: false,
      align: "canvas",
      placement: "right",
      passThresholdPercent: 0.1,
    },
    a11y: { test: "todo" },
    docs: {
      source: {
        code: exampleSources.Preview,
        language: "html",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <PreviewExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Custom separator"
  exportName="CustomSeparator"
  tags={["upstream-example", "visual-approved"]}
  parameters={{
    visualDelta: {
      images: [
        "/visual-baselines/shadcn/breadcrumb/custom-separator-chromium-darwin.png",
      ],
      opacity: 0.5,
      colorInversion: false,
      align: "canvas",
      placement: "right",
      passThresholdPercent: 0.1,
    },
    a11y: { test: "todo" },
    docs: {
      description: {
        story:
          "Use a custom component in the `slot` of `` to create a custom separator.",
      },
      source: {
        code: exampleSources.CustomSeparator,
        language: "html",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <CustomSeparatorExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Dropdown"
  exportName="Dropdown"
  tags={["upstream-example", "visual-approved"]}
  parameters={{
    visualDelta: {
      images: [
        "/visual-baselines/shadcn/breadcrumb/dropdown-chromium-darwin.png",
      ],
      opacity: 0.5,
      colorInversion: false,
      align: "canvas",
      placement: "right",
      passThresholdPercent: 0.1,
    },
    a11y: { test: "todo" },
    docs: {
      description: {
        story:
          "You can compose `` with a `` to create a dropdown in the breadcrumb.",
      },
      source: {
        code: exampleSources.Dropdown,
        language: "html",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <DropdownExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Collapsed"
  exportName="Collapsed"
  tags={["upstream-example", "visual-approved"]}
  parameters={{
    visualDelta: {
      images: [
        "/visual-baselines/shadcn/breadcrumb/collapsed-chromium-darwin.png",
      ],
      opacity: 0.5,
      colorInversion: false,
      align: "canvas",
      placement: "right",
      passThresholdPercent: 0.1,
    },
    a11y: { test: "todo" },
    docs: {
      description: {
        story:
          "We provide a `` component to show a collapsed state when the breadcrumb is too long.",
      },
      source: {
        code: exampleSources.Collapsed,
        language: "html",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <CollapsedExample />
    </div>
  {/snippet}
</Story>

<Story
  name="Link component"
  exportName="LinkComponent"
  tags={["upstream-example", "visual-approved"]}
  parameters={{
    visualDelta: {
      images: [
        "/visual-baselines/shadcn/breadcrumb/link-component-chromium-darwin.png",
      ],
      opacity: 0.5,
      colorInversion: false,
      align: "canvas",
      placement: "right",
      passThresholdPercent: 0.1,
    },
    a11y: { test: "todo" },
    docs: {
      description: {
        story: "To use a link just add the `href` prop to ``.",
      },
      source: {
        code: exampleSources.LinkComponent,
        language: "html",
        type: "code",
      },
    },
  }}
>
  {#snippet template()}
    <div class="p-4">
      <LinkComponentExample />
    </div>
  {/snippet}
</Story>
